// protoc --go_out=. --go-grpc_out=. proto/proto.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: proto/proto.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FlightStates struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlightId      string                 `protobuf:"bytes,1,opt,name=flight_id,json=flightId,proto3" json:"flight_id,omitempty"`
	UpdateType    string                 `protobuf:"bytes,2,opt,name=update_type,json=updateType,proto3" json:"update_type,omitempty"`
	UpdateValue   string                 `protobuf:"bytes,3,opt,name=update_value,json=updateValue,proto3" json:"update_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlightStates) Reset() {
	*x = FlightStates{}
	mi := &file_proto_proto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlightStates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlightStates) ProtoMessage() {}

func (x *FlightStates) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlightStates.ProtoReflect.Descriptor instead.
func (*FlightStates) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{0}
}

func (x *FlightStates) GetFlightId() string {
	if x != nil {
		return x.FlightId
	}
	return ""
}

func (x *FlightStates) GetUpdateType() string {
	if x != nil {
		return x.UpdateType
	}
	return ""
}

func (x *FlightStates) GetUpdateValue() string {
	if x != nil {
		return x.UpdateValue
	}
	return ""
}

type MRReadRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FlightId        string                 `protobuf:"bytes,1,opt,name=flight_id,json=flightId,proto3" json:"flight_id,omitempty"`
	ClientId        string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	LastVersionSeen int64                  `protobuf:"varint,3,opt,name=last_version_seen,json=lastVersionSeen,proto3" json:"last_version_seen,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MRReadRequest) Reset() {
	*x = MRReadRequest{}
	mi := &file_proto_proto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MRReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MRReadRequest) ProtoMessage() {}

func (x *MRReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MRReadRequest.ProtoReflect.Descriptor instead.
func (*MRReadRequest) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{1}
}

func (x *MRReadRequest) GetFlightId() string {
	if x != nil {
		return x.FlightId
	}
	return ""
}

func (x *MRReadRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *MRReadRequest) GetLastVersionSeen() int64 {
	if x != nil {
		return x.LastVersionSeen
	}
	return 0
}

type MRReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlightId      string                 `protobuf:"bytes,1,opt,name=flight_id,json=flightId,proto3" json:"flight_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Gate          string                 `protobuf:"bytes,3,opt,name=gate,proto3" json:"gate,omitempty"`
	Version       int64                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	Success       bool                   `protobuf:"varint,5,opt,name=success,proto3" json:"success,omitempty"`
	Msg           string                 `protobuf:"bytes,6,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MRReadResponse) Reset() {
	*x = MRReadResponse{}
	mi := &file_proto_proto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MRReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MRReadResponse) ProtoMessage() {}

func (x *MRReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MRReadResponse.ProtoReflect.Descriptor instead.
func (*MRReadResponse) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{2}
}

func (x *MRReadResponse) GetFlightId() string {
	if x != nil {
		return x.FlightId
	}
	return ""
}

func (x *MRReadResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MRReadResponse) GetGate() string {
	if x != nil {
		return x.Gate
	}
	return ""
}

func (x *MRReadResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *MRReadResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MRReadResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type Infov struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Estado        string                 `protobuf:"bytes,2,opt,name=estado,proto3" json:"estado,omitempty"`
	Puerta        string                 `protobuf:"bytes,3,opt,name=puerta,proto3" json:"puerta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Infov) Reset() {
	*x = Infov{}
	mi := &file_proto_proto_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Infov) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Infov) ProtoMessage() {}

func (x *Infov) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Infov.ProtoReflect.Descriptor instead.
func (*Infov) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{3}
}

func (x *Infov) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Infov) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

func (x *Infov) GetPuerta() string {
	if x != nil {
		return x.Puerta
	}
	return ""
}

type Infoa struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	FlightID      string                 `protobuf:"bytes,2,opt,name=FlightID,proto3" json:"FlightID,omitempty"`
	SeatID        string                 `protobuf:"bytes,3,opt,name=SeatID,proto3" json:"SeatID,omitempty"`
	Ocuppied      bool                   `protobuf:"varint,4,opt,name=Ocuppied,proto3" json:"Ocuppied,omitempty"`
	UserID        string                 `protobuf:"bytes,5,opt,name=userID,proto3" json:"userID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Infoa) Reset() {
	*x = Infoa{}
	mi := &file_proto_proto_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Infoa) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Infoa) ProtoMessage() {}

func (x *Infoa) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Infoa.ProtoReflect.Descriptor instead.
func (*Infoa) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{4}
}

func (x *Infoa) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Infoa) GetFlightID() string {
	if x != nil {
		return x.FlightID
	}
	return ""
}

func (x *Infoa) GetSeatID() string {
	if x != nil {
		return x.SeatID
	}
	return ""
}

func (x *Infoa) GetOcuppied() bool {
	if x != nil {
		return x.Ocuppied
	}
	return false
}

func (x *Infoa) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flag          int64                  `protobuf:"varint,1,opt,name=flag,proto3" json:"flag,omitempty"` // 0 si no hay cambio, 1 si el solicitante esta desactualizado, 2 si el receptor esta desactualizado, 3 concurrencia
	Datosv        []*Infov               `protobuf:"bytes,2,rep,name=datosv,proto3" json:"datosv,omitempty"`
	Datosa        []*Infoa               `protobuf:"bytes,3,rep,name=datosa,proto3" json:"datosa,omitempty"`
	R             *Reloj                 `protobuf:"bytes,4,opt,name=R,proto3" json:"R,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_proto_proto_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{5}
}

func (x *Data) GetFlag() int64 {
	if x != nil {
		return x.Flag
	}
	return 0
}

func (x *Data) GetDatosv() []*Infov {
	if x != nil {
		return x.Datosv
	}
	return nil
}

func (x *Data) GetDatosa() []*Infoa {
	if x != nil {
		return x.Datosa
	}
	return nil
}

func (x *Data) GetR() *Reloj {
	if x != nil {
		return x.R
	}
	return nil
}

type Reloj struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	R0            int64                  `protobuf:"varint,1,opt,name=R0,proto3" json:"R0,omitempty"`
	R1            int64                  `protobuf:"varint,2,opt,name=R1,proto3" json:"R1,omitempty"`
	R2            int64                  `protobuf:"varint,3,opt,name=R2,proto3" json:"R2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reloj) Reset() {
	*x = Reloj{}
	mi := &file_proto_proto_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reloj) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reloj) ProtoMessage() {}

func (x *Reloj) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reloj.ProtoReflect.Descriptor instead.
func (*Reloj) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{6}
}

func (x *Reloj) GetR0() int64 {
	if x != nil {
		return x.R0
	}
	return 0
}

func (x *Reloj) GetR1() int64 {
	if x != nil {
		return x.R1
	}
	return 0
}

func (x *Reloj) GetR2() int64 {
	if x != nil {
		return x.R2
	}
	return 0
}

// Coordinador
type CoordinadorWriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClienteId     string                 `protobuf:"bytes,1,opt,name=cliente_id,json=clienteId,proto3" json:"cliente_id,omitempty"`
	FlightId      string                 `protobuf:"bytes,2,opt,name=flight_id,json=flightId,proto3" json:"flight_id,omitempty"`
	Seat          string                 `protobuf:"bytes,3,opt,name=seat,proto3" json:"seat,omitempty"`
	RequestId     string                 `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoordinadorWriteRequest) Reset() {
	*x = CoordinadorWriteRequest{}
	mi := &file_proto_proto_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinadorWriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinadorWriteRequest) ProtoMessage() {}

func (x *CoordinadorWriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinadorWriteRequest.ProtoReflect.Descriptor instead.
func (*CoordinadorWriteRequest) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{7}
}

func (x *CoordinadorWriteRequest) GetClienteId() string {
	if x != nil {
		return x.ClienteId
	}
	return ""
}

func (x *CoordinadorWriteRequest) GetFlightId() string {
	if x != nil {
		return x.FlightId
	}
	return ""
}

func (x *CoordinadorWriteRequest) GetSeat() string {
	if x != nil {
		return x.Seat
	}
	return ""
}

func (x *CoordinadorWriteRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type CoordinadorWriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Version       int64                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoordinadorWriteResponse) Reset() {
	*x = CoordinadorWriteResponse{}
	mi := &file_proto_proto_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinadorWriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinadorWriteResponse) ProtoMessage() {}

func (x *CoordinadorWriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinadorWriteResponse.ProtoReflect.Descriptor instead.
func (*CoordinadorWriteResponse) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{8}
}

func (x *CoordinadorWriteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CoordinadorWriteResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *CoordinadorWriteResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type GetInitialInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlightId      string                 `protobuf:"bytes,1,opt,name=flight_id,json=flightId,proto3" json:"flight_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInitialInfoRequest) Reset() {
	*x = GetInitialInfoRequest{}
	mi := &file_proto_proto_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInitialInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInitialInfoRequest) ProtoMessage() {}

func (x *GetInitialInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInitialInfoRequest.ProtoReflect.Descriptor instead.
func (*GetInitialInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{9}
}

func (x *GetInitialInfoRequest) GetFlightId() string {
	if x != nil {
		return x.FlightId
	}
	return ""
}

type GetInitialInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seats         string                 `protobuf:"bytes,1,opt,name=seats,proto3" json:"seats,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Msg           string                 `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInitialInfoResponse) Reset() {
	*x = GetInitialInfoResponse{}
	mi := &file_proto_proto_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInitialInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInitialInfoResponse) ProtoMessage() {}

func (x *GetInitialInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInitialInfoResponse.ProtoReflect.Descriptor instead.
func (*GetInitialInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{10}
}

func (x *GetInitialInfoResponse) GetSeats() string {
	if x != nil {
		return x.Seats
	}
	return ""
}

func (x *GetInitialInfoResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetInitialInfoResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type BrokerReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlightId      string                 `protobuf:"bytes,1,opt,name=flight_id,json=flightId,proto3" json:"flight_id,omitempty"`
	DatanodeId    int64                  `protobuf:"varint,2,opt,name=datanode_id,json=datanodeId,proto3" json:"datanode_id,omitempty"`
	ClienteId     string                 `protobuf:"bytes,3,opt,name=cliente_id,json=clienteId,proto3" json:"cliente_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrokerReadRequest) Reset() {
	*x = BrokerReadRequest{}
	mi := &file_proto_proto_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrokerReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrokerReadRequest) ProtoMessage() {}

func (x *BrokerReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrokerReadRequest.ProtoReflect.Descriptor instead.
func (*BrokerReadRequest) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{11}
}

func (x *BrokerReadRequest) GetFlightId() string {
	if x != nil {
		return x.FlightId
	}
	return ""
}

func (x *BrokerReadRequest) GetDatanodeId() int64 {
	if x != nil {
		return x.DatanodeId
	}
	return 0
}

func (x *BrokerReadRequest) GetClienteId() string {
	if x != nil {
		return x.ClienteId
	}
	return ""
}

type BrokerReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlightId      string                 `protobuf:"bytes,1,opt,name=flight_id,json=flightId,proto3" json:"flight_id,omitempty"`
	Seat          string                 `protobuf:"bytes,2,opt,name=seat,proto3" json:"seat,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Gate          string                 `protobuf:"bytes,4,opt,name=gate,proto3" json:"gate,omitempty"`
	Version       int64                  `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	Success       bool                   `protobuf:"varint,6,opt,name=success,proto3" json:"success,omitempty"`
	Msg           string                 `protobuf:"bytes,7,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrokerReadResponse) Reset() {
	*x = BrokerReadResponse{}
	mi := &file_proto_proto_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrokerReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrokerReadResponse) ProtoMessage() {}

func (x *BrokerReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrokerReadResponse.ProtoReflect.Descriptor instead.
func (*BrokerReadResponse) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{12}
}

func (x *BrokerReadResponse) GetFlightId() string {
	if x != nil {
		return x.FlightId
	}
	return ""
}

func (x *BrokerReadResponse) GetSeat() string {
	if x != nil {
		return x.Seat
	}
	return ""
}

func (x *BrokerReadResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *BrokerReadResponse) GetGate() string {
	if x != nil {
		return x.Gate
	}
	return ""
}

func (x *BrokerReadResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *BrokerReadResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BrokerReadResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type Vacio struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vacio) Reset() {
	*x = Vacio{}
	mi := &file_proto_proto_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vacio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vacio) ProtoMessage() {}

func (x *Vacio) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vacio.ProtoReflect.Descriptor instead.
func (*Vacio) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{13}
}

var File_proto_proto_proto protoreflect.FileDescriptor

const file_proto_proto_proto_rawDesc = "" +
	"\n" +
	"\x11proto/proto.proto\x12\bAeroDist\"o\n" +
	"\fFlightStates\x12\x1b\n" +
	"\tflight_id\x18\x01 \x01(\tR\bflightId\x12\x1f\n" +
	"\vupdate_type\x18\x02 \x01(\tR\n" +
	"updateType\x12!\n" +
	"\fupdate_value\x18\x03 \x01(\tR\vupdateValue\"u\n" +
	"\rMRReadRequest\x12\x1b\n" +
	"\tflight_id\x18\x01 \x01(\tR\bflightId\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12*\n" +
	"\x11last_version_seen\x18\x03 \x01(\x03R\x0flastVersionSeen\"\x9f\x01\n" +
	"\x0eMRReadResponse\x12\x1b\n" +
	"\tflight_id\x18\x01 \x01(\tR\bflightId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x12\n" +
	"\x04gate\x18\x03 \x01(\tR\x04gate\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x03R\aversion\x12\x18\n" +
	"\asuccess\x18\x05 \x01(\bR\asuccess\x12\x10\n" +
	"\x03msg\x18\x06 \x01(\tR\x03msg\"G\n" +
	"\x05Infov\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x16\n" +
	"\x06estado\x18\x02 \x01(\tR\x06estado\x12\x16\n" +
	"\x06puerta\x18\x03 \x01(\tR\x06puerta\"\x7f\n" +
	"\x05Infoa\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x1a\n" +
	"\bFlightID\x18\x02 \x01(\tR\bFlightID\x12\x16\n" +
	"\x06SeatID\x18\x03 \x01(\tR\x06SeatID\x12\x1a\n" +
	"\bOcuppied\x18\x04 \x01(\bR\bOcuppied\x12\x16\n" +
	"\x06userID\x18\x05 \x01(\tR\x06userID\"\x8b\x01\n" +
	"\x04Data\x12\x12\n" +
	"\x04flag\x18\x01 \x01(\x03R\x04flag\x12'\n" +
	"\x06datosv\x18\x02 \x03(\v2\x0f.AeroDist.InfovR\x06datosv\x12'\n" +
	"\x06datosa\x18\x03 \x03(\v2\x0f.AeroDist.InfoaR\x06datosa\x12\x1d\n" +
	"\x01R\x18\x04 \x01(\v2\x0f.AeroDist.RelojR\x01R\"7\n" +
	"\x05Reloj\x12\x0e\n" +
	"\x02R0\x18\x01 \x01(\x03R\x02R0\x12\x0e\n" +
	"\x02R1\x18\x02 \x01(\x03R\x02R1\x12\x0e\n" +
	"\x02R2\x18\x03 \x01(\x03R\x02R2\"\x88\x01\n" +
	"\x17CoordinadorWriteRequest\x12\x1d\n" +
	"\n" +
	"cliente_id\x18\x01 \x01(\tR\tclienteId\x12\x1b\n" +
	"\tflight_id\x18\x02 \x01(\tR\bflightId\x12\x12\n" +
	"\x04seat\x18\x03 \x01(\tR\x04seat\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\"`\n" +
	"\x18CoordinadorWriteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x03R\aversion\"4\n" +
	"\x15GetInitialInfoRequest\x12\x1b\n" +
	"\tflight_id\x18\x01 \x01(\tR\bflightId\"Z\n" +
	"\x16GetInitialInfoResponse\x12\x14\n" +
	"\x05seats\x18\x01 \x01(\tR\x05seats\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x10\n" +
	"\x03msg\x18\x03 \x01(\tR\x03msg\"p\n" +
	"\x11BrokerReadRequest\x12\x1b\n" +
	"\tflight_id\x18\x01 \x01(\tR\bflightId\x12\x1f\n" +
	"\vdatanode_id\x18\x02 \x01(\x03R\n" +
	"datanodeId\x12\x1d\n" +
	"\n" +
	"cliente_id\x18\x03 \x01(\tR\tclienteId\"\xb7\x01\n" +
	"\x12BrokerReadResponse\x12\x1b\n" +
	"\tflight_id\x18\x01 \x01(\tR\bflightId\x12\x12\n" +
	"\x04seat\x18\x02 \x01(\tR\x04seat\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x12\n" +
	"\x04gate\x18\x04 \x01(\tR\x04gate\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x03R\aversion\x12\x18\n" +
	"\asuccess\x18\x06 \x01(\bR\asuccess\x12\x10\n" +
	"\x03msg\x18\a \x01(\tR\x03msg\"\a\n" +
	"\x05Vacio2\xdc\x03\n" +
	"\bDatanode\x127\n" +
	"\fFlightUpdate\x12\x16.AeroDist.FlightStates\x1a\x0f.AeroDist.Vacio\x12.\n" +
	"\n" +
	"ApagarNodo\x12\x0f.AeroDist.Vacio\x1a\x0f.AeroDist.Vacio\x12;\n" +
	"\x06MRRead\x12\x17.AeroDist.MRReadRequest\x1a\x18.AeroDist.MRReadResponse\x121\n" +
	"\x0fCompararRelojes\x12\x0e.AeroDist.Data\x1a\x0e.AeroDist.Data\x12Y\n" +
	"\x10CoordinadorWrite\x12!.AeroDist.CoordinadorWriteRequest\x1a\".AeroDist.CoordinadorWriteResponse\x12S\n" +
	"\x0eGetInitialInfo\x12\x1f.AeroDist.GetInitialInfoRequest\x1a .AeroDist.GetInitialInfoResponse\x12G\n" +
	"\n" +
	"BrokerRead\x12\x1b.AeroDist.BrokerReadRequest\x1a\x1c.AeroDist.BrokerReadResponseB\bZ\x06/protob\x06proto3"

var (
	file_proto_proto_proto_rawDescOnce sync.Once
	file_proto_proto_proto_rawDescData []byte
)

func file_proto_proto_proto_rawDescGZIP() []byte {
	file_proto_proto_proto_rawDescOnce.Do(func() {
		file_proto_proto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_proto_proto_rawDesc), len(file_proto_proto_proto_rawDesc)))
	})
	return file_proto_proto_proto_rawDescData
}

var file_proto_proto_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_proto_proto_goTypes = []any{
	(*FlightStates)(nil),             // 0: AeroDist.FlightStates
	(*MRReadRequest)(nil),            // 1: AeroDist.MRReadRequest
	(*MRReadResponse)(nil),           // 2: AeroDist.MRReadResponse
	(*Infov)(nil),                    // 3: AeroDist.Infov
	(*Infoa)(nil),                    // 4: AeroDist.Infoa
	(*Data)(nil),                     // 5: AeroDist.Data
	(*Reloj)(nil),                    // 6: AeroDist.Reloj
	(*CoordinadorWriteRequest)(nil),  // 7: AeroDist.CoordinadorWriteRequest
	(*CoordinadorWriteResponse)(nil), // 8: AeroDist.CoordinadorWriteResponse
	(*GetInitialInfoRequest)(nil),    // 9: AeroDist.GetInitialInfoRequest
	(*GetInitialInfoResponse)(nil),   // 10: AeroDist.GetInitialInfoResponse
	(*BrokerReadRequest)(nil),        // 11: AeroDist.BrokerReadRequest
	(*BrokerReadResponse)(nil),       // 12: AeroDist.BrokerReadResponse
	(*Vacio)(nil),                    // 13: AeroDist.Vacio
}
var file_proto_proto_proto_depIdxs = []int32{
	3,  // 0: AeroDist.Data.datosv:type_name -> AeroDist.Infov
	4,  // 1: AeroDist.Data.datosa:type_name -> AeroDist.Infoa
	6,  // 2: AeroDist.Data.R:type_name -> AeroDist.Reloj
	0,  // 3: AeroDist.Datanode.FlightUpdate:input_type -> AeroDist.FlightStates
	13, // 4: AeroDist.Datanode.ApagarNodo:input_type -> AeroDist.Vacio
	1,  // 5: AeroDist.Datanode.MRRead:input_type -> AeroDist.MRReadRequest
	5,  // 6: AeroDist.Datanode.CompararRelojes:input_type -> AeroDist.Data
	7,  // 7: AeroDist.Datanode.CoordinadorWrite:input_type -> AeroDist.CoordinadorWriteRequest
	9,  // 8: AeroDist.Datanode.GetInitialInfo:input_type -> AeroDist.GetInitialInfoRequest
	11, // 9: AeroDist.Datanode.BrokerRead:input_type -> AeroDist.BrokerReadRequest
	13, // 10: AeroDist.Datanode.FlightUpdate:output_type -> AeroDist.Vacio
	13, // 11: AeroDist.Datanode.ApagarNodo:output_type -> AeroDist.Vacio
	2,  // 12: AeroDist.Datanode.MRRead:output_type -> AeroDist.MRReadResponse
	5,  // 13: AeroDist.Datanode.CompararRelojes:output_type -> AeroDist.Data
	8,  // 14: AeroDist.Datanode.CoordinadorWrite:output_type -> AeroDist.CoordinadorWriteResponse
	10, // 15: AeroDist.Datanode.GetInitialInfo:output_type -> AeroDist.GetInitialInfoResponse
	12, // 16: AeroDist.Datanode.BrokerRead:output_type -> AeroDist.BrokerReadResponse
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_proto_proto_init() }
func file_proto_proto_proto_init() {
	if File_proto_proto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_proto_proto_rawDesc), len(file_proto_proto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_proto_proto_goTypes,
		DependencyIndexes: file_proto_proto_proto_depIdxs,
		MessageInfos:      file_proto_proto_proto_msgTypes,
	}.Build()
	File_proto_proto_proto = out.File
	file_proto_proto_proto_goTypes = nil
	file_proto_proto_proto_depIdxs = nil
}
