// se compila con desde /lab2:
// protoc --go_out=. --go-grpc_out=. proto/proto.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.32.0
// source: proto/proto.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Broker_GenerarOferta_FullMethodName    = "/CyberDay.Broker/GenerarOferta"
	Broker_Registrarse_FullMethodName      = "/CyberDay.Broker/Registrarse"
	Broker_GenerarHistorico_FullMethodName = "/CyberDay.Broker/GenerarHistorico"
)

// BrokerClient is the client API for Broker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BrokerClient interface {
	GenerarOferta(ctx context.Context, in *Oferta, opts ...grpc.CallOption) (*Bool, error)
	Registrarse(ctx context.Context, in *Registro, opts ...grpc.CallOption) (*Bool, error)
	GenerarHistorico(ctx context.Context, in *Registro, opts ...grpc.CallOption) (*RangeSinceResponse, error)
}

type brokerClient struct {
	cc grpc.ClientConnInterface
}

func NewBrokerClient(cc grpc.ClientConnInterface) BrokerClient {
	return &brokerClient{cc}
}

func (c *brokerClient) GenerarOferta(ctx context.Context, in *Oferta, opts ...grpc.CallOption) (*Bool, error) {
	out := new(Bool)
	err := c.cc.Invoke(ctx, Broker_GenerarOferta_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerClient) Registrarse(ctx context.Context, in *Registro, opts ...grpc.CallOption) (*Bool, error) {
	out := new(Bool)
	err := c.cc.Invoke(ctx, Broker_Registrarse_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerClient) GenerarHistorico(ctx context.Context, in *Registro, opts ...grpc.CallOption) (*RangeSinceResponse, error) {
	out := new(RangeSinceResponse)
	err := c.cc.Invoke(ctx, Broker_GenerarHistorico_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BrokerServer is the server API for Broker service.
// All implementations must embed UnimplementedBrokerServer
// for forward compatibility
type BrokerServer interface {
	GenerarOferta(context.Context, *Oferta) (*Bool, error)
	Registrarse(context.Context, *Registro) (*Bool, error)
	GenerarHistorico(context.Context, *Registro) (*RangeSinceResponse, error)
	mustEmbedUnimplementedBrokerServer()
}

// UnimplementedBrokerServer must be embedded to have forward compatible implementations.
type UnimplementedBrokerServer struct {
}

func (UnimplementedBrokerServer) GenerarOferta(context.Context, *Oferta) (*Bool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerarOferta not implemented")
}
func (UnimplementedBrokerServer) Registrarse(context.Context, *Registro) (*Bool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Registrarse not implemented")
}
func (UnimplementedBrokerServer) GenerarHistorico(context.Context, *Registro) (*RangeSinceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerarHistorico not implemented")
}
func (UnimplementedBrokerServer) mustEmbedUnimplementedBrokerServer() {}

// UnsafeBrokerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BrokerServer will
// result in compilation errors.
type UnsafeBrokerServer interface {
	mustEmbedUnimplementedBrokerServer()
}

func RegisterBrokerServer(s grpc.ServiceRegistrar, srv BrokerServer) {
	s.RegisterService(&Broker_ServiceDesc, srv)
}

func _Broker_GenerarOferta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Oferta)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServer).GenerarOferta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Broker_GenerarOferta_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServer).GenerarOferta(ctx, req.(*Oferta))
	}
	return interceptor(ctx, in, info, handler)
}

func _Broker_Registrarse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Registro)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServer).Registrarse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Broker_Registrarse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServer).Registrarse(ctx, req.(*Registro))
	}
	return interceptor(ctx, in, info, handler)
}

func _Broker_GenerarHistorico_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Registro)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServer).GenerarHistorico(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Broker_GenerarHistorico_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServer).GenerarHistorico(ctx, req.(*Registro))
	}
	return interceptor(ctx, in, info, handler)
}

// Broker_ServiceDesc is the grpc.ServiceDesc for Broker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Broker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "CyberDay.Broker",
	HandlerType: (*BrokerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerarOferta",
			Handler:    _Broker_GenerarOferta_Handler,
		},
		{
			MethodName: "Registrarse",
			Handler:    _Broker_Registrarse_Handler,
		},
		{
			MethodName: "GenerarHistorico",
			Handler:    _Broker_GenerarHistorico_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/proto.proto",
}

const (
	NodeService_GuardarOferta_FullMethodName = "/CyberDay.NodeService/GuardarOferta"
)

// NodeServiceClient is the client API for NodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodeServiceClient interface {
	GuardarOferta(ctx context.Context, in *Oferta, opts ...grpc.CallOption) (*Bool, error)
}

type nodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeServiceClient(cc grpc.ClientConnInterface) NodeServiceClient {
	return &nodeServiceClient{cc}
}

func (c *nodeServiceClient) GuardarOferta(ctx context.Context, in *Oferta, opts ...grpc.CallOption) (*Bool, error) {
	out := new(Bool)
	err := c.cc.Invoke(ctx, NodeService_GuardarOferta_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeServiceServer is the server API for NodeService service.
// All implementations must embed UnimplementedNodeServiceServer
// for forward compatibility
type NodeServiceServer interface {
	GuardarOferta(context.Context, *Oferta) (*Bool, error)
	mustEmbedUnimplementedNodeServiceServer()
}

// UnimplementedNodeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedNodeServiceServer struct {
}

func (UnimplementedNodeServiceServer) GuardarOferta(context.Context, *Oferta) (*Bool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GuardarOferta not implemented")
}
func (UnimplementedNodeServiceServer) mustEmbedUnimplementedNodeServiceServer() {}

// UnsafeNodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeServiceServer will
// result in compilation errors.
type UnsafeNodeServiceServer interface {
	mustEmbedUnimplementedNodeServiceServer()
}

func RegisterNodeServiceServer(s grpc.ServiceRegistrar, srv NodeServiceServer) {
	s.RegisterService(&NodeService_ServiceDesc, srv)
}

func _NodeService_GuardarOferta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Oferta)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).GuardarOferta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_GuardarOferta_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).GuardarOferta(ctx, req.(*Oferta))
	}
	return interceptor(ctx, in, info, handler)
}

// NodeService_ServiceDesc is the grpc.ServiceDesc for NodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "CyberDay.NodeService",
	HandlerType: (*NodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GuardarOferta",
			Handler:    _NodeService_GuardarOferta_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/proto.proto",
}

const (
	Consumidor_NotificarOferta_FullMethodName = "/CyberDay.Consumidor/NotificarOferta"
)

// ConsumidorClient is the client API for Consumidor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConsumidorClient interface {
	NotificarOferta(ctx context.Context, in *Oferta, opts ...grpc.CallOption) (*Bool, error)
}

type consumidorClient struct {
	cc grpc.ClientConnInterface
}

func NewConsumidorClient(cc grpc.ClientConnInterface) ConsumidorClient {
	return &consumidorClient{cc}
}

func (c *consumidorClient) NotificarOferta(ctx context.Context, in *Oferta, opts ...grpc.CallOption) (*Bool, error) {
	out := new(Bool)
	err := c.cc.Invoke(ctx, Consumidor_NotificarOferta_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConsumidorServer is the server API for Consumidor service.
// All implementations must embed UnimplementedConsumidorServer
// for forward compatibility
type ConsumidorServer interface {
	NotificarOferta(context.Context, *Oferta) (*Bool, error)
	mustEmbedUnimplementedConsumidorServer()
}

// UnimplementedConsumidorServer must be embedded to have forward compatible implementations.
type UnimplementedConsumidorServer struct {
}

func (UnimplementedConsumidorServer) NotificarOferta(context.Context, *Oferta) (*Bool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotificarOferta not implemented")
}
func (UnimplementedConsumidorServer) mustEmbedUnimplementedConsumidorServer() {}

// UnsafeConsumidorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConsumidorServer will
// result in compilation errors.
type UnsafeConsumidorServer interface {
	mustEmbedUnimplementedConsumidorServer()
}

func RegisterConsumidorServer(s grpc.ServiceRegistrar, srv ConsumidorServer) {
	s.RegisterService(&Consumidor_ServiceDesc, srv)
}

func _Consumidor_NotificarOferta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Oferta)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsumidorServer).NotificarOferta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Consumidor_NotificarOferta_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsumidorServer).NotificarOferta(ctx, req.(*Oferta))
	}
	return interceptor(ctx, in, info, handler)
}

// Consumidor_ServiceDesc is the grpc.ServiceDesc for Consumidor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Consumidor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "CyberDay.Consumidor",
	HandlerType: (*ConsumidorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NotificarOferta",
			Handler:    _Consumidor_NotificarOferta_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/proto.proto",
}
