// se compila con desde /lab2:
// protoc --go_out=. --go-grpc_out=. proto/proto.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v6.32.0
// source: proto/proto.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Registro struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nombre string `protobuf:"bytes,1,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Rol    int32  `protobuf:"varint,2,opt,name=rol,proto3" json:"rol,omitempty"` //Tienda = 0, Consumidor = 1
}

func (x *Registro) Reset() {
	*x = Registro{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_proto_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Registro) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Registro) ProtoMessage() {}

func (x *Registro) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Registro.ProtoReflect.Descriptor instead.
func (*Registro) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{0}
}

func (x *Registro) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *Registro) GetRol() int32 {
	if x != nil {
		return x.Rol
	}
	return 0
}

type Oferta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OfertaId  string `protobuf:"bytes,1,opt,name=oferta_id,json=ofertaId,proto3" json:"oferta_id,omitempty"`
	Tienda    string `protobuf:"bytes,2,opt,name=tienda,proto3" json:"tienda,omitempty"`
	Categoria string `protobuf:"bytes,3,opt,name=categoria,proto3" json:"categoria,omitempty"`
	Producto  string `protobuf:"bytes,4,opt,name=producto,proto3" json:"producto,omitempty"`
	Precio    int64  `protobuf:"varint,5,opt,name=precio,proto3" json:"precio,omitempty"`
	Stock     int64  `protobuf:"varint,6,opt,name=stock,proto3" json:"stock,omitempty"`
	Fecha     string `protobuf:"bytes,7,opt,name=fecha,proto3" json:"fecha,omitempty"`
}

func (x *Oferta) Reset() {
	*x = Oferta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_proto_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Oferta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Oferta) ProtoMessage() {}

func (x *Oferta) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Oferta.ProtoReflect.Descriptor instead.
func (*Oferta) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{1}
}

func (x *Oferta) GetOfertaId() string {
	if x != nil {
		return x.OfertaId
	}
	return ""
}

func (x *Oferta) GetTienda() string {
	if x != nil {
		return x.Tienda
	}
	return ""
}

func (x *Oferta) GetCategoria() string {
	if x != nil {
		return x.Categoria
	}
	return ""
}

func (x *Oferta) GetProducto() string {
	if x != nil {
		return x.Producto
	}
	return ""
}

func (x *Oferta) GetPrecio() int64 {
	if x != nil {
		return x.Precio
	}
	return 0
}

func (x *Oferta) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *Oferta) GetFecha() string {
	if x != nil {
		return x.Fecha
	}
	return ""
}

type Bool struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flag bool `protobuf:"varint,1,opt,name=flag,proto3" json:"flag,omitempty"`
}

func (x *Bool) Reset() {
	*x = Bool{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_proto_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bool) ProtoMessage() {}

func (x *Bool) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bool.ProtoReflect.Descriptor instead.
func (*Bool) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{2}
}

func (x *Bool) GetFlag() bool {
	if x != nil {
		return x.Flag
	}
	return false
}

type Vacio struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Vacio) Reset() {
	*x = Vacio{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_proto_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Vacio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vacio) ProtoMessage() {}

func (x *Vacio) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vacio.ProtoReflect.Descriptor instead.
func (*Vacio) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{3}
}

type RangeSinceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ofertas []*Oferta `protobuf:"bytes,1,rep,name=Ofertas,proto3" json:"Ofertas,omitempty"`
}

func (x *RangeSinceResponse) Reset() {
	*x = RangeSinceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_proto_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RangeSinceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeSinceResponse) ProtoMessage() {}

func (x *RangeSinceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeSinceResponse.ProtoReflect.Descriptor instead.
func (*RangeSinceResponse) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{4}
}

func (x *RangeSinceResponse) GetOfertas() []*Oferta {
	if x != nil {
		return x.Ofertas
	}
	return nil
}

type DatosFinalesConsumidor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id               string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OfertasRecibidas int64  `protobuf:"varint,2,opt,name=ofertasRecibidas,proto3" json:"ofertasRecibidas,omitempty"`
	NombreCSV        string `protobuf:"bytes,3,opt,name=nombreCSV,proto3" json:"nombreCSV,omitempty"`
}

func (x *DatosFinalesConsumidor) Reset() {
	*x = DatosFinalesConsumidor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_proto_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DatosFinalesConsumidor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatosFinalesConsumidor) ProtoMessage() {}

func (x *DatosFinalesConsumidor) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatosFinalesConsumidor.ProtoReflect.Descriptor instead.
func (*DatosFinalesConsumidor) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{5}
}

func (x *DatosFinalesConsumidor) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DatosFinalesConsumidor) GetOfertasRecibidas() int64 {
	if x != nil {
		return x.OfertasRecibidas
	}
	return 0
}

func (x *DatosFinalesConsumidor) GetNombreCSV() string {
	if x != nil {
		return x.NombreCSV
	}
	return ""
}

var File_proto_proto_proto protoreflect.FileDescriptor

var file_proto_proto_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x08, 0x43, 0x79, 0x62, 0x65, 0x72, 0x44, 0x61, 0x79, 0x22, 0x34, 0x0a,
	0x08, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x6d,
	0x62, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x6f, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03,
	0x72, 0x6f, 0x6c, 0x22, 0xbb, 0x01, 0x0a, 0x06, 0x4f, 0x66, 0x65, 0x72, 0x74, 0x61, 0x12, 0x1b,
	0x0a, 0x09, 0x6f, 0x66, 0x65, 0x72, 0x74, 0x61, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x6f, 0x66, 0x65, 0x72, 0x74, 0x61, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x74,
	0x69, 0x65, 0x6e, 0x64, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x69, 0x65,
	0x6e, 0x64, 0x61, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x61,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69,
	0x61, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x6f, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x6f, 0x12, 0x16, 0x0a,
	0x06, 0x70, 0x72, 0x65, 0x63, 0x69, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x70,
	0x72, 0x65, 0x63, 0x69, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x66,
	0x65, 0x63, 0x68, 0x61, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x66, 0x65, 0x63, 0x68,
	0x61, 0x22, 0x1a, 0x0a, 0x04, 0x42, 0x6f, 0x6f, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x6c, 0x61,
	0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x22, 0x07, 0x0a,
	0x05, 0x56, 0x61, 0x63, 0x69, 0x6f, 0x22, 0x40, 0x0a, 0x12, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x53,
	0x69, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x07,
	0x4f, 0x66, 0x65, 0x72, 0x74, 0x61, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x43, 0x79, 0x62, 0x65, 0x72, 0x44, 0x61, 0x79, 0x2e, 0x4f, 0x66, 0x65, 0x72, 0x74, 0x61, 0x52,
	0x07, 0x4f, 0x66, 0x65, 0x72, 0x74, 0x61, 0x73, 0x22, 0x72, 0x0a, 0x16, 0x44, 0x61, 0x74, 0x6f,
	0x73, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x65, 0x73, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x69, 0x64,
	0x6f, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x2a, 0x0a, 0x10, 0x6f, 0x66, 0x65, 0x72, 0x74, 0x61, 0x73, 0x52, 0x65, 0x63,
	0x69, 0x62, 0x69, 0x64, 0x61, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x10, 0x6f, 0x66,
	0x65, 0x72, 0x74, 0x61, 0x73, 0x52, 0x65, 0x63, 0x69, 0x62, 0x69, 0x64, 0x61, 0x73, 0x12, 0x1c,
	0x0a, 0x09, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x43, 0x53, 0x56, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x43, 0x53, 0x56, 0x32, 0xea, 0x01, 0x0a,
	0x06, 0x42, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x12, 0x33, 0x0a, 0x0d, 0x47, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x72, 0x4f, 0x66, 0x65, 0x72, 0x74, 0x61, 0x12, 0x10, 0x2e, 0x43, 0x79, 0x62, 0x65, 0x72,
	0x44, 0x61, 0x79, 0x2e, 0x4f, 0x66, 0x65, 0x72, 0x74, 0x61, 0x1a, 0x0e, 0x2e, 0x43, 0x79, 0x62,
	0x65, 0x72, 0x44, 0x61, 0x79, 0x2e, 0x42, 0x6f, 0x6f, 0x6c, 0x22, 0x00, 0x12, 0x33, 0x0a, 0x0b,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x72, 0x73, 0x65, 0x12, 0x12, 0x2e, 0x43, 0x79,
	0x62, 0x65, 0x72, 0x44, 0x61, 0x79, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x6f, 0x1a,
	0x0e, 0x2e, 0x43, 0x79, 0x62, 0x65, 0x72, 0x44, 0x61, 0x79, 0x2e, 0x42, 0x6f, 0x6f, 0x6c, 0x22,
	0x00, 0x12, 0x46, 0x0a, 0x10, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x72, 0x48, 0x69, 0x73, 0x74,
	0x6f, 0x72, 0x69, 0x63, 0x6f, 0x12, 0x12, 0x2e, 0x43, 0x79, 0x62, 0x65, 0x72, 0x44, 0x61, 0x79,
	0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x6f, 0x1a, 0x1c, 0x2e, 0x43, 0x79, 0x62, 0x65,
	0x72, 0x44, 0x61, 0x79, 0x2e, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x53, 0x69, 0x6e, 0x63, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x2e, 0x0a, 0x06, 0x41, 0x63, 0x74,
	0x69, 0x76, 0x6f, 0x12, 0x12, 0x2e, 0x43, 0x79, 0x62, 0x65, 0x72, 0x44, 0x61, 0x79, 0x2e, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x6f, 0x1a, 0x0e, 0x2e, 0x43, 0x79, 0x62, 0x65, 0x72, 0x44,
	0x61, 0x79, 0x2e, 0x42, 0x6f, 0x6f, 0x6c, 0x22, 0x00, 0x32, 0x42, 0x0a, 0x0b, 0x4e, 0x6f, 0x64,
	0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x33, 0x0a, 0x0d, 0x47, 0x75, 0x61, 0x72,
	0x64, 0x61, 0x72, 0x4f, 0x66, 0x65, 0x72, 0x74, 0x61, 0x12, 0x10, 0x2e, 0x43, 0x79, 0x62, 0x65,
	0x72, 0x44, 0x61, 0x79, 0x2e, 0x4f, 0x66, 0x65, 0x72, 0x74, 0x61, 0x1a, 0x0e, 0x2e, 0x43, 0x79,
	0x62, 0x65, 0x72, 0x44, 0x61, 0x79, 0x2e, 0x42, 0x6f, 0x6f, 0x6c, 0x22, 0x00, 0x32, 0x82, 0x01,
	0x0a, 0x0a, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x69, 0x64, 0x6f, 0x72, 0x12, 0x33, 0x0a, 0x0f,
	0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x72, 0x4f, 0x66, 0x65, 0x72, 0x74, 0x61, 0x12,
	0x10, 0x2e, 0x43, 0x79, 0x62, 0x65, 0x72, 0x44, 0x61, 0x79, 0x2e, 0x4f, 0x66, 0x65, 0x72, 0x74,
	0x61, 0x1a, 0x0e, 0x2e, 0x43, 0x79, 0x62, 0x65, 0x72, 0x44, 0x61, 0x79, 0x2e, 0x42, 0x6f, 0x6f,
	0x6c, 0x12, 0x3f, 0x0a, 0x0a, 0x70, 0x65, 0x64, 0x69, 0x72, 0x44, 0x61, 0x74, 0x6f, 0x73, 0x12,
	0x0f, 0x2e, 0x43, 0x79, 0x62, 0x65, 0x72, 0x44, 0x61, 0x79, 0x2e, 0x56, 0x61, 0x63, 0x69, 0x6f,
	0x1a, 0x20, 0x2e, 0x43, 0x79, 0x62, 0x65, 0x72, 0x44, 0x61, 0x79, 0x2e, 0x44, 0x61, 0x74, 0x6f,
	0x73, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x65, 0x73, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x69, 0x64,
	0x6f, 0x72, 0x42, 0x08, 0x5a, 0x06, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_proto_proto_rawDescOnce sync.Once
	file_proto_proto_proto_rawDescData = file_proto_proto_proto_rawDesc
)

func file_proto_proto_proto_rawDescGZIP() []byte {
	file_proto_proto_proto_rawDescOnce.Do(func() {
		file_proto_proto_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_proto_proto_rawDescData)
	})
	return file_proto_proto_proto_rawDescData
}

var file_proto_proto_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_proto_proto_goTypes = []interface{}{
	(*Registro)(nil),               // 0: CyberDay.Registro
	(*Oferta)(nil),                 // 1: CyberDay.Oferta
	(*Bool)(nil),                   // 2: CyberDay.Bool
	(*Vacio)(nil),                  // 3: CyberDay.Vacio
	(*RangeSinceResponse)(nil),     // 4: CyberDay.RangeSinceResponse
	(*DatosFinalesConsumidor)(nil), // 5: CyberDay.DatosFinalesConsumidor
}
var file_proto_proto_proto_depIdxs = []int32{
	1, // 0: CyberDay.RangeSinceResponse.Ofertas:type_name -> CyberDay.Oferta
	1, // 1: CyberDay.Broker.GenerarOferta:input_type -> CyberDay.Oferta
	0, // 2: CyberDay.Broker.Registrarse:input_type -> CyberDay.Registro
	0, // 3: CyberDay.Broker.GenerarHistorico:input_type -> CyberDay.Registro
	0, // 4: CyberDay.Broker.Activo:input_type -> CyberDay.Registro
	1, // 5: CyberDay.NodeService.GuardarOferta:input_type -> CyberDay.Oferta
	1, // 6: CyberDay.Consumidor.NotificarOferta:input_type -> CyberDay.Oferta
	3, // 7: CyberDay.Consumidor.pedirDatos:input_type -> CyberDay.Vacio
	2, // 8: CyberDay.Broker.GenerarOferta:output_type -> CyberDay.Bool
	2, // 9: CyberDay.Broker.Registrarse:output_type -> CyberDay.Bool
	4, // 10: CyberDay.Broker.GenerarHistorico:output_type -> CyberDay.RangeSinceResponse
	2, // 11: CyberDay.Broker.Activo:output_type -> CyberDay.Bool
	2, // 12: CyberDay.NodeService.GuardarOferta:output_type -> CyberDay.Bool
	2, // 13: CyberDay.Consumidor.NotificarOferta:output_type -> CyberDay.Bool
	5, // 14: CyberDay.Consumidor.pedirDatos:output_type -> CyberDay.DatosFinalesConsumidor
	8, // [8:15] is the sub-list for method output_type
	1, // [1:8] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_proto_proto_init() }
func file_proto_proto_proto_init() {
	if File_proto_proto_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_proto_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Registro); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_proto_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Oferta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_proto_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bool); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_proto_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Vacio); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_proto_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RangeSinceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_proto_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DatosFinalesConsumidor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_proto_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_proto_proto_proto_goTypes,
		DependencyIndexes: file_proto_proto_proto_depIdxs,
		MessageInfos:      file_proto_proto_proto_msgTypes,
	}.Build()
	File_proto_proto_proto = out.File
	file_proto_proto_proto_rawDesc = nil
	file_proto_proto_proto_goTypes = nil
	file_proto_proto_proto_depIdxs = nil
}
