// protoc --go_out=. --go-grpc_out=. proto/proto.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: proto/proto.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Seat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeatId        string                 `protobuf:"bytes,1,opt,name=seatId,proto3" json:"seatId,omitempty"`
	Occupied      bool                   `protobuf:"varint,2,opt,name=occupied,proto3" json:"occupied,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Seat) Reset() {
	*x = Seat{}
	mi := &file_proto_proto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Seat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Seat) ProtoMessage() {}

func (x *Seat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Seat.ProtoReflect.Descriptor instead.
func (*Seat) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{0}
}

func (x *Seat) GetSeatId() string {
	if x != nil {
		return x.SeatId
	}
	return ""
}

func (x *Seat) GetOccupied() bool {
	if x != nil {
		return x.Occupied
	}
	return false
}

type Flight struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlightId      string                 `protobuf:"bytes,1,opt,name=flight_id,json=flightId,proto3" json:"flight_id,omitempty"`
	Seats         []*Seat                `protobuf:"bytes,2,rep,name=seats,proto3" json:"seats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Flight) Reset() {
	*x = Flight{}
	mi := &file_proto_proto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Flight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Flight) ProtoMessage() {}

func (x *Flight) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Flight.ProtoReflect.Descriptor instead.
func (*Flight) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{1}
}

func (x *Flight) GetFlightId() string {
	if x != nil {
		return x.FlightId
	}
	return ""
}

func (x *Flight) GetSeats() []*Seat {
	if x != nil {
		return x.Seats
	}
	return nil
}

type Flights struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flights       []*Flight              `protobuf:"bytes,1,rep,name=flights,proto3" json:"flights,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Flights) Reset() {
	*x = Flights{}
	mi := &file_proto_proto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Flights) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Flights) ProtoMessage() {}

func (x *Flights) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Flights.ProtoReflect.Descriptor instead.
func (*Flights) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{2}
}

func (x *Flights) GetFlights() []*Flight {
	if x != nil {
		return x.Flights
	}
	return nil
}

type MRReadRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FlightId        string                 `protobuf:"bytes,1,opt,name=flight_id,json=flightId,proto3" json:"flight_id,omitempty"`
	ClientId        string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	LastVersionSeen int64                  `protobuf:"varint,3,opt,name=last_version_seen,json=lastVersionSeen,proto3" json:"last_version_seen,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MRReadRequest) Reset() {
	*x = MRReadRequest{}
	mi := &file_proto_proto_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MRReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MRReadRequest) ProtoMessage() {}

func (x *MRReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MRReadRequest.ProtoReflect.Descriptor instead.
func (*MRReadRequest) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{3}
}

func (x *MRReadRequest) GetFlightId() string {
	if x != nil {
		return x.FlightId
	}
	return ""
}

func (x *MRReadRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *MRReadRequest) GetLastVersionSeen() int64 {
	if x != nil {
		return x.LastVersionSeen
	}
	return 0
}

type MRReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlightId      string                 `protobuf:"bytes,1,opt,name=flight_id,json=flightId,proto3" json:"flight_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Gate          string                 `protobuf:"bytes,3,opt,name=gate,proto3" json:"gate,omitempty"`
	Version       int64                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	Success       bool                   `protobuf:"varint,5,opt,name=success,proto3" json:"success,omitempty"`
	Msg           string                 `protobuf:"bytes,6,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MRReadResponse) Reset() {
	*x = MRReadResponse{}
	mi := &file_proto_proto_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MRReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MRReadResponse) ProtoMessage() {}

func (x *MRReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MRReadResponse.ProtoReflect.Descriptor instead.
func (*MRReadResponse) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{4}
}

func (x *MRReadResponse) GetFlightId() string {
	if x != nil {
		return x.FlightId
	}
	return ""
}

func (x *MRReadResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MRReadResponse) GetGate() string {
	if x != nil {
		return x.Gate
	}
	return ""
}

func (x *MRReadResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *MRReadResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MRReadResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type GetInitialInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlightId      string                 `protobuf:"bytes,1,opt,name=flight_id,json=flightId,proto3" json:"flight_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInitialInfoRequest) Reset() {
	*x = GetInitialInfoRequest{}
	mi := &file_proto_proto_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInitialInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInitialInfoRequest) ProtoMessage() {}

func (x *GetInitialInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInitialInfoRequest.ProtoReflect.Descriptor instead.
func (*GetInitialInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{5}
}

func (x *GetInitialInfoRequest) GetFlightId() string {
	if x != nil {
		return x.FlightId
	}
	return ""
}

type GetInitialInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seats         string                 `protobuf:"bytes,1,opt,name=seats,proto3" json:"seats,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Msg           string                 `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInitialInfoResponse) Reset() {
	*x = GetInitialInfoResponse{}
	mi := &file_proto_proto_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInitialInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInitialInfoResponse) ProtoMessage() {}

func (x *GetInitialInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInitialInfoResponse.ProtoReflect.Descriptor instead.
func (*GetInitialInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{6}
}

func (x *GetInitialInfoResponse) GetSeats() string {
	if x != nil {
		return x.Seats
	}
	return ""
}

func (x *GetInitialInfoResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetInitialInfoResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type ApplyWriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClienteId     string                 `protobuf:"bytes,1,opt,name=cliente_id,json=clienteId,proto3" json:"cliente_id,omitempty"`
	FlightId      string                 `protobuf:"bytes,2,opt,name=flight_id,json=flightId,proto3" json:"flight_id,omitempty"`
	Seat          string                 `protobuf:"bytes,3,opt,name=seat,proto3" json:"seat,omitempty"`
	RequestId     string                 `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyWriteRequest) Reset() {
	*x = ApplyWriteRequest{}
	mi := &file_proto_proto_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyWriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyWriteRequest) ProtoMessage() {}

func (x *ApplyWriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyWriteRequest.ProtoReflect.Descriptor instead.
func (*ApplyWriteRequest) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{7}
}

func (x *ApplyWriteRequest) GetClienteId() string {
	if x != nil {
		return x.ClienteId
	}
	return ""
}

func (x *ApplyWriteRequest) GetFlightId() string {
	if x != nil {
		return x.FlightId
	}
	return ""
}

func (x *ApplyWriteRequest) GetSeat() string {
	if x != nil {
		return x.Seat
	}
	return ""
}

func (x *ApplyWriteRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type ApplyWriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	DatonodeId    string                 `protobuf:"bytes,3,opt,name=datonode_id,json=datonodeId,proto3" json:"datonode_id,omitempty"`
	Version       int64                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyWriteResponse) Reset() {
	*x = ApplyWriteResponse{}
	mi := &file_proto_proto_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyWriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyWriteResponse) ProtoMessage() {}

func (x *ApplyWriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyWriteResponse.ProtoReflect.Descriptor instead.
func (*ApplyWriteResponse) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{8}
}

func (x *ApplyWriteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ApplyWriteResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ApplyWriteResponse) GetDatonodeId() string {
	if x != nil {
		return x.DatonodeId
	}
	return ""
}

func (x *ApplyWriteResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type BrokerReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlightId      string                 `protobuf:"bytes,1,opt,name=flight_id,json=flightId,proto3" json:"flight_id,omitempty"`
	DatanodeId    string                 `protobuf:"bytes,2,opt,name=datanode_id,json=datanodeId,proto3" json:"datanode_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrokerReadRequest) Reset() {
	*x = BrokerReadRequest{}
	mi := &file_proto_proto_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrokerReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrokerReadRequest) ProtoMessage() {}

func (x *BrokerReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrokerReadRequest.ProtoReflect.Descriptor instead.
func (*BrokerReadRequest) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{9}
}

func (x *BrokerReadRequest) GetFlightId() string {
	if x != nil {
		return x.FlightId
	}
	return ""
}

func (x *BrokerReadRequest) GetDatanodeId() string {
	if x != nil {
		return x.DatanodeId
	}
	return ""
}

type BrokerReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlightId      string                 `protobuf:"bytes,1,opt,name=flight_id,json=flightId,proto3" json:"flight_id,omitempty"`
	Seat          string                 `protobuf:"bytes,2,opt,name=seat,proto3" json:"seat,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Gate          string                 `protobuf:"bytes,4,opt,name=gate,proto3" json:"gate,omitempty"`
	Version       int64                  `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	Success       bool                   `protobuf:"varint,6,opt,name=success,proto3" json:"success,omitempty"`
	Msg           string                 `protobuf:"bytes,7,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrokerReadResponse) Reset() {
	*x = BrokerReadResponse{}
	mi := &file_proto_proto_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrokerReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrokerReadResponse) ProtoMessage() {}

func (x *BrokerReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrokerReadResponse.ProtoReflect.Descriptor instead.
func (*BrokerReadResponse) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{10}
}

func (x *BrokerReadResponse) GetFlightId() string {
	if x != nil {
		return x.FlightId
	}
	return ""
}

func (x *BrokerReadResponse) GetSeat() string {
	if x != nil {
		return x.Seat
	}
	return ""
}

func (x *BrokerReadResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *BrokerReadResponse) GetGate() string {
	if x != nil {
		return x.Gate
	}
	return ""
}

func (x *BrokerReadResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *BrokerReadResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BrokerReadResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type FlightStates struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlightId      string                 `protobuf:"bytes,1,opt,name=flight_id,json=flightId,proto3" json:"flight_id,omitempty"`
	UpdateType    string                 `protobuf:"bytes,2,opt,name=update_type,json=updateType,proto3" json:"update_type,omitempty"`
	UpdateValue   string                 `protobuf:"bytes,3,opt,name=update_value,json=updateValue,proto3" json:"update_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlightStates) Reset() {
	*x = FlightStates{}
	mi := &file_proto_proto_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlightStates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlightStates) ProtoMessage() {}

func (x *FlightStates) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlightStates.ProtoReflect.Descriptor instead.
func (*FlightStates) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{11}
}

func (x *FlightStates) GetFlightId() string {
	if x != nil {
		return x.FlightId
	}
	return ""
}

func (x *FlightStates) GetUpdateType() string {
	if x != nil {
		return x.UpdateType
	}
	return ""
}

func (x *FlightStates) GetUpdateValue() string {
	if x != nil {
		return x.UpdateValue
	}
	return ""
}

type CoordinadorWriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClienteId     string                 `protobuf:"bytes,1,opt,name=cliente_id,json=clienteId,proto3" json:"cliente_id,omitempty"`
	FlightId      string                 `protobuf:"bytes,2,opt,name=flight_id,json=flightId,proto3" json:"flight_id,omitempty"`
	Seat          string                 `protobuf:"bytes,3,opt,name=seat,proto3" json:"seat,omitempty"`
	RequestId     string                 `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoordinadorWriteRequest) Reset() {
	*x = CoordinadorWriteRequest{}
	mi := &file_proto_proto_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinadorWriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinadorWriteRequest) ProtoMessage() {}

func (x *CoordinadorWriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinadorWriteRequest.ProtoReflect.Descriptor instead.
func (*CoordinadorWriteRequest) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{12}
}

func (x *CoordinadorWriteRequest) GetClienteId() string {
	if x != nil {
		return x.ClienteId
	}
	return ""
}

func (x *CoordinadorWriteRequest) GetFlightId() string {
	if x != nil {
		return x.FlightId
	}
	return ""
}

func (x *CoordinadorWriteRequest) GetSeat() string {
	if x != nil {
		return x.Seat
	}
	return ""
}

func (x *CoordinadorWriteRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type CoordinadorWriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Version       int64                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoordinadorWriteResponse) Reset() {
	*x = CoordinadorWriteResponse{}
	mi := &file_proto_proto_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinadorWriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinadorWriteResponse) ProtoMessage() {}

func (x *CoordinadorWriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinadorWriteResponse.ProtoReflect.Descriptor instead.
func (*CoordinadorWriteResponse) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{13}
}

func (x *CoordinadorWriteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CoordinadorWriteResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *CoordinadorWriteResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type Vacio struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vacio) Reset() {
	*x = Vacio{}
	mi := &file_proto_proto_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vacio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vacio) ProtoMessage() {}

func (x *Vacio) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vacio.ProtoReflect.Descriptor instead.
func (*Vacio) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{14}
}

var File_proto_proto_proto protoreflect.FileDescriptor

const file_proto_proto_proto_rawDesc = "" +
	"\n" +
	"\x11proto/proto.proto\x12\bAeroDist\":\n" +
	"\x04Seat\x12\x16\n" +
	"\x06seatId\x18\x01 \x01(\tR\x06seatId\x12\x1a\n" +
	"\boccupied\x18\x02 \x01(\bR\boccupied\"K\n" +
	"\x06Flight\x12\x1b\n" +
	"\tflight_id\x18\x01 \x01(\tR\bflightId\x12$\n" +
	"\x05seats\x18\x02 \x03(\v2\x0e.AeroDist.SeatR\x05seats\"5\n" +
	"\aFlights\x12*\n" +
	"\aflights\x18\x01 \x03(\v2\x10.AeroDist.FlightR\aflights\"u\n" +
	"\rMRReadRequest\x12\x1b\n" +
	"\tflight_id\x18\x01 \x01(\tR\bflightId\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12*\n" +
	"\x11last_version_seen\x18\x03 \x01(\x03R\x0flastVersionSeen\"\x9f\x01\n" +
	"\x0eMRReadResponse\x12\x1b\n" +
	"\tflight_id\x18\x01 \x01(\tR\bflightId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x12\n" +
	"\x04gate\x18\x03 \x01(\tR\x04gate\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x03R\aversion\x12\x18\n" +
	"\asuccess\x18\x05 \x01(\bR\asuccess\x12\x10\n" +
	"\x03msg\x18\x06 \x01(\tR\x03msg\"4\n" +
	"\x15GetInitialInfoRequest\x12\x1b\n" +
	"\tflight_id\x18\x01 \x01(\tR\bflightId\"Z\n" +
	"\x16GetInitialInfoResponse\x12\x14\n" +
	"\x05seats\x18\x01 \x01(\tR\x05seats\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x10\n" +
	"\x03msg\x18\x03 \x01(\tR\x03msg\"\x82\x01\n" +
	"\x11ApplyWriteRequest\x12\x1d\n" +
	"\n" +
	"cliente_id\x18\x01 \x01(\tR\tclienteId\x12\x1b\n" +
	"\tflight_id\x18\x02 \x01(\tR\bflightId\x12\x12\n" +
	"\x04seat\x18\x03 \x01(\tR\x04seat\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\"{\n" +
	"\x12ApplyWriteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x1f\n" +
	"\vdatonode_id\x18\x03 \x01(\tR\n" +
	"datonodeId\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x03R\aversion\"Q\n" +
	"\x11BrokerReadRequest\x12\x1b\n" +
	"\tflight_id\x18\x01 \x01(\tR\bflightId\x12\x1f\n" +
	"\vdatanode_id\x18\x02 \x01(\tR\n" +
	"datanodeId\"\xb7\x01\n" +
	"\x12BrokerReadResponse\x12\x1b\n" +
	"\tflight_id\x18\x01 \x01(\tR\bflightId\x12\x12\n" +
	"\x04seat\x18\x02 \x01(\tR\x04seat\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x12\n" +
	"\x04gate\x18\x04 \x01(\tR\x04gate\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x03R\aversion\x12\x18\n" +
	"\asuccess\x18\x06 \x01(\bR\asuccess\x12\x10\n" +
	"\x03msg\x18\a \x01(\tR\x03msg\"o\n" +
	"\fFlightStates\x12\x1b\n" +
	"\tflight_id\x18\x01 \x01(\tR\bflightId\x12\x1f\n" +
	"\vupdate_type\x18\x02 \x01(\tR\n" +
	"updateType\x12!\n" +
	"\fupdate_value\x18\x03 \x01(\tR\vupdateValue\"\x88\x01\n" +
	"\x17CoordinadorWriteRequest\x12\x1d\n" +
	"\n" +
	"cliente_id\x18\x01 \x01(\tR\tclienteId\x12\x1b\n" +
	"\tflight_id\x18\x02 \x01(\tR\bflightId\x12\x12\n" +
	"\x04seat\x18\x03 \x01(\tR\x04seat\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\"`\n" +
	"\x18CoordinadorWriteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x03R\aversion\"\a\n" +
	"\x05Vacio2\xac\x02\n" +
	"\x06Broker\x12;\n" +
	"\x06MRRead\x12\x17.AeroDist.MRReadRequest\x1a\x18.AeroDist.MRReadResponse\x12S\n" +
	"\x0eGetInitialInfo\x12\x1f.AeroDist.GetInitialInfoRequest\x1a .AeroDist.GetInitialInfoResponse\x12G\n" +
	"\n" +
	"ApplyWrite\x12\x1b.AeroDist.ApplyWriteRequest\x1a\x1c.AeroDist.ApplyWriteResponse\x12G\n" +
	"\n" +
	"BrokerRead\x12\x1b.AeroDist.BrokerReadRequest\x1a\x1c.AeroDist.BrokerReadResponse2\x90\x02\n" +
	"\bDatanode\x127\n" +
	"\fFlightUpdate\x12\x16.AeroDist.FlightStates\x1a\x0f.AeroDist.Vacio\x123\n" +
	"\rCreateFlights\x12\x11.AeroDist.Flights\x1a\x0f.AeroDist.Vacio\x12;\n" +
	"\x06MRRead\x12\x17.AeroDist.MRReadRequest\x1a\x18.AeroDist.MRReadResponse\x12Y\n" +
	"\x10CoordinadorWrite\x12!.AeroDist.CoordinadorWriteRequest\x1a\".AeroDist.CoordinadorWriteResponseB\bZ\x06/protob\x06proto3"

var (
	file_proto_proto_proto_rawDescOnce sync.Once
	file_proto_proto_proto_rawDescData []byte
)

func file_proto_proto_proto_rawDescGZIP() []byte {
	file_proto_proto_proto_rawDescOnce.Do(func() {
		file_proto_proto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_proto_proto_rawDesc), len(file_proto_proto_proto_rawDesc)))
	})
	return file_proto_proto_proto_rawDescData
}

var file_proto_proto_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_proto_proto_goTypes = []any{
	(*Seat)(nil),                     // 0: AeroDist.Seat
	(*Flight)(nil),                   // 1: AeroDist.Flight
	(*Flights)(nil),                  // 2: AeroDist.Flights
	(*MRReadRequest)(nil),            // 3: AeroDist.MRReadRequest
	(*MRReadResponse)(nil),           // 4: AeroDist.MRReadResponse
	(*GetInitialInfoRequest)(nil),    // 5: AeroDist.GetInitialInfoRequest
	(*GetInitialInfoResponse)(nil),   // 6: AeroDist.GetInitialInfoResponse
	(*ApplyWriteRequest)(nil),        // 7: AeroDist.ApplyWriteRequest
	(*ApplyWriteResponse)(nil),       // 8: AeroDist.ApplyWriteResponse
	(*BrokerReadRequest)(nil),        // 9: AeroDist.BrokerReadRequest
	(*BrokerReadResponse)(nil),       // 10: AeroDist.BrokerReadResponse
	(*FlightStates)(nil),             // 11: AeroDist.FlightStates
	(*CoordinadorWriteRequest)(nil),  // 12: AeroDist.CoordinadorWriteRequest
	(*CoordinadorWriteResponse)(nil), // 13: AeroDist.CoordinadorWriteResponse
	(*Vacio)(nil),                    // 14: AeroDist.Vacio
}
var file_proto_proto_proto_depIdxs = []int32{
	0,  // 0: AeroDist.Flight.seats:type_name -> AeroDist.Seat
	1,  // 1: AeroDist.Flights.flights:type_name -> AeroDist.Flight
	3,  // 2: AeroDist.Broker.MRRead:input_type -> AeroDist.MRReadRequest
	5,  // 3: AeroDist.Broker.GetInitialInfo:input_type -> AeroDist.GetInitialInfoRequest
	7,  // 4: AeroDist.Broker.ApplyWrite:input_type -> AeroDist.ApplyWriteRequest
	9,  // 5: AeroDist.Broker.BrokerRead:input_type -> AeroDist.BrokerReadRequest
	11, // 6: AeroDist.Datanode.FlightUpdate:input_type -> AeroDist.FlightStates
	2,  // 7: AeroDist.Datanode.CreateFlights:input_type -> AeroDist.Flights
	3,  // 8: AeroDist.Datanode.MRRead:input_type -> AeroDist.MRReadRequest
	12, // 9: AeroDist.Datanode.CoordinadorWrite:input_type -> AeroDist.CoordinadorWriteRequest
	4,  // 10: AeroDist.Broker.MRRead:output_type -> AeroDist.MRReadResponse
	6,  // 11: AeroDist.Broker.GetInitialInfo:output_type -> AeroDist.GetInitialInfoResponse
	8,  // 12: AeroDist.Broker.ApplyWrite:output_type -> AeroDist.ApplyWriteResponse
	10, // 13: AeroDist.Broker.BrokerRead:output_type -> AeroDist.BrokerReadResponse
	14, // 14: AeroDist.Datanode.FlightUpdate:output_type -> AeroDist.Vacio
	14, // 15: AeroDist.Datanode.CreateFlights:output_type -> AeroDist.Vacio
	4,  // 16: AeroDist.Datanode.MRRead:output_type -> AeroDist.MRReadResponse
	13, // 17: AeroDist.Datanode.CoordinadorWrite:output_type -> AeroDist.CoordinadorWriteResponse
	10, // [10:18] is the sub-list for method output_type
	2,  // [2:10] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_proto_proto_init() }
func file_proto_proto_proto_init() {
	if File_proto_proto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_proto_proto_rawDesc), len(file_proto_proto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_proto_proto_goTypes,
		DependencyIndexes: file_proto_proto_proto_depIdxs,
		MessageInfos:      file_proto_proto_proto_msgTypes,
	}.Build()
	File_proto_proto_proto = out.File
	file_proto_proto_proto_goTypes = nil
	file_proto_proto_proto_depIdxs = nil
}
