// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.32.0
// source: proto/proto.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	BrokerMR_MRRead_FullMethodName = "/AeroDist.BrokerMR/MRRead"
)

// BrokerMRClient is the client API for BrokerMR service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BrokerMRClient interface {
	MRRead(ctx context.Context, in *MRReadRequest, opts ...grpc.CallOption) (*MRReadResponse, error)
}

type brokerMRClient struct {
	cc grpc.ClientConnInterface
}

func NewBrokerMRClient(cc grpc.ClientConnInterface) BrokerMRClient {
	return &brokerMRClient{cc}
}

func (c *brokerMRClient) MRRead(ctx context.Context, in *MRReadRequest, opts ...grpc.CallOption) (*MRReadResponse, error) {
	out := new(MRReadResponse)
	err := c.cc.Invoke(ctx, BrokerMR_MRRead_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BrokerMRServer is the server API for BrokerMR service.
// All implementations must embed UnimplementedBrokerMRServer
// for forward compatibility
type BrokerMRServer interface {
	MRRead(context.Context, *MRReadRequest) (*MRReadResponse, error)
	mustEmbedUnimplementedBrokerMRServer()
}

// UnimplementedBrokerMRServer must be embedded to have forward compatible implementations.
type UnimplementedBrokerMRServer struct {
}

func (UnimplementedBrokerMRServer) MRRead(context.Context, *MRReadRequest) (*MRReadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MRRead not implemented")
}
func (UnimplementedBrokerMRServer) mustEmbedUnimplementedBrokerMRServer() {}

// UnsafeBrokerMRServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BrokerMRServer will
// result in compilation errors.
type UnsafeBrokerMRServer interface {
	mustEmbedUnimplementedBrokerMRServer()
}

func RegisterBrokerMRServer(s grpc.ServiceRegistrar, srv BrokerMRServer) {
	s.RegisterService(&BrokerMR_ServiceDesc, srv)
}

func _BrokerMR_MRRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MRReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerMRServer).MRRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrokerMR_MRRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerMRServer).MRRead(ctx, req.(*MRReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BrokerMR_ServiceDesc is the grpc.ServiceDesc for BrokerMR service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BrokerMR_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "AeroDist.BrokerMR",
	HandlerType: (*BrokerMRServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MRRead",
			Handler:    _BrokerMR_MRRead_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/proto.proto",
}

const (
	BrokerCoordinador_ApplyWrite_FullMethodName = "/AeroDist.BrokerCoordinador/ApplyWrite"
	BrokerCoordinador_BrokerRead_FullMethodName = "/AeroDist.BrokerCoordinador/BrokerRead"
)

// BrokerCoordinadorClient is the client API for BrokerCoordinador service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BrokerCoordinadorClient interface {
	ApplyWrite(ctx context.Context, in *ApplyWriteRequest, opts ...grpc.CallOption) (*ApplyWriteResponse, error)
	BrokerRead(ctx context.Context, in *BrokerReadRequest, opts ...grpc.CallOption) (*BrokerReadResponse, error)
}

type brokerCoordinadorClient struct {
	cc grpc.ClientConnInterface
}

func NewBrokerCoordinadorClient(cc grpc.ClientConnInterface) BrokerCoordinadorClient {
	return &brokerCoordinadorClient{cc}
}

func (c *brokerCoordinadorClient) ApplyWrite(ctx context.Context, in *ApplyWriteRequest, opts ...grpc.CallOption) (*ApplyWriteResponse, error) {
	out := new(ApplyWriteResponse)
	err := c.cc.Invoke(ctx, BrokerCoordinador_ApplyWrite_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerCoordinadorClient) BrokerRead(ctx context.Context, in *BrokerReadRequest, opts ...grpc.CallOption) (*BrokerReadResponse, error) {
	out := new(BrokerReadResponse)
	err := c.cc.Invoke(ctx, BrokerCoordinador_BrokerRead_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BrokerCoordinadorServer is the server API for BrokerCoordinador service.
// All implementations must embed UnimplementedBrokerCoordinadorServer
// for forward compatibility
type BrokerCoordinadorServer interface {
	ApplyWrite(context.Context, *ApplyWriteRequest) (*ApplyWriteResponse, error)
	BrokerRead(context.Context, *BrokerReadRequest) (*BrokerReadResponse, error)
	mustEmbedUnimplementedBrokerCoordinadorServer()
}

// UnimplementedBrokerCoordinadorServer must be embedded to have forward compatible implementations.
type UnimplementedBrokerCoordinadorServer struct {
}

func (UnimplementedBrokerCoordinadorServer) ApplyWrite(context.Context, *ApplyWriteRequest) (*ApplyWriteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyWrite not implemented")
}
func (UnimplementedBrokerCoordinadorServer) BrokerRead(context.Context, *BrokerReadRequest) (*BrokerReadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BrokerRead not implemented")
}
func (UnimplementedBrokerCoordinadorServer) mustEmbedUnimplementedBrokerCoordinadorServer() {}

// UnsafeBrokerCoordinadorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BrokerCoordinadorServer will
// result in compilation errors.
type UnsafeBrokerCoordinadorServer interface {
	mustEmbedUnimplementedBrokerCoordinadorServer()
}

func RegisterBrokerCoordinadorServer(s grpc.ServiceRegistrar, srv BrokerCoordinadorServer) {
	s.RegisterService(&BrokerCoordinador_ServiceDesc, srv)
}

func _BrokerCoordinador_ApplyWrite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyWriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerCoordinadorServer).ApplyWrite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrokerCoordinador_ApplyWrite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerCoordinadorServer).ApplyWrite(ctx, req.(*ApplyWriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrokerCoordinador_BrokerRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BrokerReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerCoordinadorServer).BrokerRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrokerCoordinador_BrokerRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerCoordinadorServer).BrokerRead(ctx, req.(*BrokerReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BrokerCoordinador_ServiceDesc is the grpc.ServiceDesc for BrokerCoordinador service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BrokerCoordinador_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "AeroDist.BrokerCoordinador",
	HandlerType: (*BrokerCoordinadorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ApplyWrite",
			Handler:    _BrokerCoordinador_ApplyWrite_Handler,
		},
		{
			MethodName: "BrokerRead",
			Handler:    _BrokerCoordinador_BrokerRead_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/proto.proto",
}
