// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: proto/proto.proto

// protoc --go_out=. --go-grpc_out=. proto/proto.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ATC_Insert_FullMethodName            = "/AeroDist.ATC/Insert"
	ATC_PostularALider_FullMethodName    = "/AeroDist.ATC/PostularALider"
	ATC_InformarNewLider_FullMethodName  = "/AeroDist.ATC/InformarNewLider"
	ATC_Ping_FullMethodName              = "/AeroDist.ATC/Ping"
	ATC_INSERTLIDER_FullMethodName       = "/AeroDist.ATC/INSERTLIDER"
	ATC_ResultadoConsenso_FullMethodName = "/AeroDist.ATC/resultadoConsenso"
	ATC_GetHistorico_FullMethodName      = "/AeroDist.ATC/GetHistorico"
)

// ATCClient is the client API for ATC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ATCClient interface {
	// rpc para ser llamado por el broker:
	Insert(ctx context.Context, in *Record, opts ...grpc.CallOption) (*InsertResponse, error)
	// rpc entre nodos (PRIV):
	PostularALider(ctx context.Context, in *Postulante, opts ...grpc.CallOption) (*NewLider, error)
	InformarNewLider(ctx context.Context, in *Postulante, opts ...grpc.CallOption) (*NewLider, error)
	Ping(ctx context.Context, in *Vacio, opts ...grpc.CallOption) (*Vacio, error)
	INSERTLIDER(ctx context.Context, in *RecordID, opts ...grpc.CallOption) (*Vacio, error)
	ResultadoConsenso(ctx context.Context, in *Record, opts ...grpc.CallOption) (*Vacio, error)
	GetHistorico(ctx context.Context, in *Vacio, opts ...grpc.CallOption) (*Historico, error)
}

type aTCClient struct {
	cc grpc.ClientConnInterface
}

func NewATCClient(cc grpc.ClientConnInterface) ATCClient {
	return &aTCClient{cc}
}

func (c *aTCClient) Insert(ctx context.Context, in *Record, opts ...grpc.CallOption) (*InsertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InsertResponse)
	err := c.cc.Invoke(ctx, ATC_Insert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aTCClient) PostularALider(ctx context.Context, in *Postulante, opts ...grpc.CallOption) (*NewLider, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewLider)
	err := c.cc.Invoke(ctx, ATC_PostularALider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aTCClient) InformarNewLider(ctx context.Context, in *Postulante, opts ...grpc.CallOption) (*NewLider, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewLider)
	err := c.cc.Invoke(ctx, ATC_InformarNewLider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aTCClient) Ping(ctx context.Context, in *Vacio, opts ...grpc.CallOption) (*Vacio, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Vacio)
	err := c.cc.Invoke(ctx, ATC_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aTCClient) INSERTLIDER(ctx context.Context, in *RecordID, opts ...grpc.CallOption) (*Vacio, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Vacio)
	err := c.cc.Invoke(ctx, ATC_INSERTLIDER_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aTCClient) ResultadoConsenso(ctx context.Context, in *Record, opts ...grpc.CallOption) (*Vacio, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Vacio)
	err := c.cc.Invoke(ctx, ATC_ResultadoConsenso_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aTCClient) GetHistorico(ctx context.Context, in *Vacio, opts ...grpc.CallOption) (*Historico, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Historico)
	err := c.cc.Invoke(ctx, ATC_GetHistorico_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ATCServer is the server API for ATC service.
// All implementations must embed UnimplementedATCServer
// for forward compatibility.
type ATCServer interface {
	// rpc para ser llamado por el broker:
	Insert(context.Context, *Record) (*InsertResponse, error)
	// rpc entre nodos (PRIV):
	PostularALider(context.Context, *Postulante) (*NewLider, error)
	InformarNewLider(context.Context, *Postulante) (*NewLider, error)
	Ping(context.Context, *Vacio) (*Vacio, error)
	INSERTLIDER(context.Context, *RecordID) (*Vacio, error)
	ResultadoConsenso(context.Context, *Record) (*Vacio, error)
	GetHistorico(context.Context, *Vacio) (*Historico, error)
	mustEmbedUnimplementedATCServer()
}

// UnimplementedATCServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedATCServer struct{}

func (UnimplementedATCServer) Insert(context.Context, *Record) (*InsertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Insert not implemented")
}
func (UnimplementedATCServer) PostularALider(context.Context, *Postulante) (*NewLider, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostularALider not implemented")
}
func (UnimplementedATCServer) InformarNewLider(context.Context, *Postulante) (*NewLider, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InformarNewLider not implemented")
}
func (UnimplementedATCServer) Ping(context.Context, *Vacio) (*Vacio, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedATCServer) INSERTLIDER(context.Context, *RecordID) (*Vacio, error) {
	return nil, status.Errorf(codes.Unimplemented, "method INSERTLIDER not implemented")
}
func (UnimplementedATCServer) ResultadoConsenso(context.Context, *Record) (*Vacio, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResultadoConsenso not implemented")
}
func (UnimplementedATCServer) GetHistorico(context.Context, *Vacio) (*Historico, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHistorico not implemented")
}
func (UnimplementedATCServer) mustEmbedUnimplementedATCServer() {}
func (UnimplementedATCServer) testEmbeddedByValue()             {}

// UnsafeATCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ATCServer will
// result in compilation errors.
type UnsafeATCServer interface {
	mustEmbedUnimplementedATCServer()
}

func RegisterATCServer(s grpc.ServiceRegistrar, srv ATCServer) {
	// If the following call pancis, it indicates UnimplementedATCServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ATC_ServiceDesc, srv)
}

func _ATC_Insert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Record)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ATCServer).Insert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ATC_Insert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ATCServer).Insert(ctx, req.(*Record))
	}
	return interceptor(ctx, in, info, handler)
}

func _ATC_PostularALider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Postulante)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ATCServer).PostularALider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ATC_PostularALider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ATCServer).PostularALider(ctx, req.(*Postulante))
	}
	return interceptor(ctx, in, info, handler)
}

func _ATC_InformarNewLider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Postulante)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ATCServer).InformarNewLider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ATC_InformarNewLider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ATCServer).InformarNewLider(ctx, req.(*Postulante))
	}
	return interceptor(ctx, in, info, handler)
}

func _ATC_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Vacio)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ATCServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ATC_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ATCServer).Ping(ctx, req.(*Vacio))
	}
	return interceptor(ctx, in, info, handler)
}

func _ATC_INSERTLIDER_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ATCServer).INSERTLIDER(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ATC_INSERTLIDER_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ATCServer).INSERTLIDER(ctx, req.(*RecordID))
	}
	return interceptor(ctx, in, info, handler)
}

func _ATC_ResultadoConsenso_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Record)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ATCServer).ResultadoConsenso(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ATC_ResultadoConsenso_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ATCServer).ResultadoConsenso(ctx, req.(*Record))
	}
	return interceptor(ctx, in, info, handler)
}

func _ATC_GetHistorico_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Vacio)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ATCServer).GetHistorico(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ATC_GetHistorico_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ATCServer).GetHistorico(ctx, req.(*Vacio))
	}
	return interceptor(ctx, in, info, handler)
}

// ATC_ServiceDesc is the grpc.ServiceDesc for ATC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ATC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "AeroDist.ATC",
	HandlerType: (*ATCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Insert",
			Handler:    _ATC_Insert_Handler,
		},
		{
			MethodName: "PostularALider",
			Handler:    _ATC_PostularALider_Handler,
		},
		{
			MethodName: "InformarNewLider",
			Handler:    _ATC_InformarNewLider_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _ATC_Ping_Handler,
		},
		{
			MethodName: "INSERTLIDER",
			Handler:    _ATC_INSERTLIDER_Handler,
		},
		{
			MethodName: "resultadoConsenso",
			Handler:    _ATC_ResultadoConsenso_Handler,
		},
		{
			MethodName: "GetHistorico",
			Handler:    _ATC_GetHistorico_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/proto.proto",
}
