// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: proto/proto.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NodoBDConsenso_INSERT_FullMethodName           = "/AeroDist.NodoBDConsenso/INSERT"
	NodoBDConsenso_PostularALider_FullMethodName   = "/AeroDist.NodoBDConsenso/PostularALider"
	NodoBDConsenso_InformarNewLider_FullMethodName = "/AeroDist.NodoBDConsenso/InformarNewLider"
)

// NodoBDConsensoClient is the client API for NodoBDConsenso service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodoBDConsensoClient interface {
	INSERT(ctx context.Context, in *Record, opts ...grpc.CallOption) (*Bool, error)
	// si alguien se cae y no tiene un lider definido, llamara a
	// PostularALider, si los dos le responden que el newlider
	// tiene un id distinto al suyo asume que ese es el lider actual
	PostularALider(ctx context.Context, in *Postulante, opts ...grpc.CallOption) (*NewLider, error)
	InformarNewLider(ctx context.Context, in *Postulante, opts ...grpc.CallOption) (*NewLider, error)
}

type nodoBDConsensoClient struct {
	cc grpc.ClientConnInterface
}

func NewNodoBDConsensoClient(cc grpc.ClientConnInterface) NodoBDConsensoClient {
	return &nodoBDConsensoClient{cc}
}

func (c *nodoBDConsensoClient) INSERT(ctx context.Context, in *Record, opts ...grpc.CallOption) (*Bool, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Bool)
	err := c.cc.Invoke(ctx, NodoBDConsenso_INSERT_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodoBDConsensoClient) PostularALider(ctx context.Context, in *Postulante, opts ...grpc.CallOption) (*NewLider, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewLider)
	err := c.cc.Invoke(ctx, NodoBDConsenso_PostularALider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodoBDConsensoClient) InformarNewLider(ctx context.Context, in *Postulante, opts ...grpc.CallOption) (*NewLider, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewLider)
	err := c.cc.Invoke(ctx, NodoBDConsenso_InformarNewLider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodoBDConsensoServer is the server API for NodoBDConsenso service.
// All implementations must embed UnimplementedNodoBDConsensoServer
// for forward compatibility.
type NodoBDConsensoServer interface {
	INSERT(context.Context, *Record) (*Bool, error)
	// si alguien se cae y no tiene un lider definido, llamara a
	// PostularALider, si los dos le responden que el newlider
	// tiene un id distinto al suyo asume que ese es el lider actual
	PostularALider(context.Context, *Postulante) (*NewLider, error)
	InformarNewLider(context.Context, *Postulante) (*NewLider, error)
	mustEmbedUnimplementedNodoBDConsensoServer()
}

// UnimplementedNodoBDConsensoServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodoBDConsensoServer struct{}

func (UnimplementedNodoBDConsensoServer) INSERT(context.Context, *Record) (*Bool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method INSERT not implemented")
}
func (UnimplementedNodoBDConsensoServer) PostularALider(context.Context, *Postulante) (*NewLider, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostularALider not implemented")
}
func (UnimplementedNodoBDConsensoServer) InformarNewLider(context.Context, *Postulante) (*NewLider, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InformarNewLider not implemented")
}
func (UnimplementedNodoBDConsensoServer) mustEmbedUnimplementedNodoBDConsensoServer() {}
func (UnimplementedNodoBDConsensoServer) testEmbeddedByValue()                        {}

// UnsafeNodoBDConsensoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodoBDConsensoServer will
// result in compilation errors.
type UnsafeNodoBDConsensoServer interface {
	mustEmbedUnimplementedNodoBDConsensoServer()
}

func RegisterNodoBDConsensoServer(s grpc.ServiceRegistrar, srv NodoBDConsensoServer) {
	// If the following call pancis, it indicates UnimplementedNodoBDConsensoServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodoBDConsenso_ServiceDesc, srv)
}

func _NodoBDConsenso_INSERT_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Record)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodoBDConsensoServer).INSERT(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodoBDConsenso_INSERT_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodoBDConsensoServer).INSERT(ctx, req.(*Record))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodoBDConsenso_PostularALider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Postulante)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodoBDConsensoServer).PostularALider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodoBDConsenso_PostularALider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodoBDConsensoServer).PostularALider(ctx, req.(*Postulante))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodoBDConsenso_InformarNewLider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Postulante)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodoBDConsensoServer).InformarNewLider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodoBDConsenso_InformarNewLider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodoBDConsensoServer).InformarNewLider(ctx, req.(*Postulante))
	}
	return interceptor(ctx, in, info, handler)
}

// NodoBDConsenso_ServiceDesc is the grpc.ServiceDesc for NodoBDConsenso service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodoBDConsenso_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "AeroDist.NodoBDConsenso",
	HandlerType: (*NodoBDConsensoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "INSERT",
			Handler:    _NodoBDConsenso_INSERT_Handler,
		},
		{
			MethodName: "PostularALider",
			Handler:    _NodoBDConsenso_PostularALider_Handler,
		},
		{
			MethodName: "InformarNewLider",
			Handler:    _NodoBDConsenso_InformarNewLider_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/proto.proto",
}
