services:
  trevor:
    build: ./Trevor
    container_name: trevor
    ports:
      - "50054:50054"
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      AMQP_URI: amqp://guest:guest@dist042.inf.santiago.usm.cl:5672/