// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: example.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CordinationService_Cordination_FullMethodName = "/example.CordinationService/Cordination"
)

// CordinationServiceClient is the client API for CordinationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CordinationServiceClient interface {
	Cordination(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type cordinationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCordinationServiceClient(cc grpc.ClientConnInterface) CordinationServiceClient {
	return &cordinationServiceClient{cc}
}

func (c *cordinationServiceClient) Cordination(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, CordinationService_Cordination_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CordinationServiceServer is the server API for CordinationService service.
// All implementations must embed UnimplementedCordinationServiceServer
// for forward compatibility.
type CordinationServiceServer interface {
	Cordination(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedCordinationServiceServer()
}

// UnimplementedCordinationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCordinationServiceServer struct{}

func (UnimplementedCordinationServiceServer) Cordination(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Cordination not implemented")
}
func (UnimplementedCordinationServiceServer) mustEmbedUnimplementedCordinationServiceServer() {}
func (UnimplementedCordinationServiceServer) testEmbeddedByValue()                            {}

// UnsafeCordinationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CordinationServiceServer will
// result in compilation errors.
type UnsafeCordinationServiceServer interface {
	mustEmbedUnimplementedCordinationServiceServer()
}

func RegisterCordinationServiceServer(s grpc.ServiceRegistrar, srv CordinationServiceServer) {
	// If the following call pancis, it indicates UnimplementedCordinationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CordinationService_ServiceDesc, srv)
}

func _CordinationService_Cordination_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CordinationServiceServer).Cordination(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CordinationService_Cordination_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CordinationServiceServer).Cordination(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// CordinationService_ServiceDesc is the grpc.ServiceDesc for CordinationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CordinationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "example.CordinationService",
	HandlerType: (*CordinationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Cordination",
			Handler:    _CordinationService_Cordination_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "example.proto",
}
