// se compila con desde /lab2:
// protoc --go_out=. --go-grpc_out=. proto/proto.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: proto/proto.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Broker_GenerarOferta_FullMethodName    = "/CyberDay.Broker/GenerarOferta"
	Broker_Registrarse_FullMethodName      = "/CyberDay.Broker/Registrarse"
	Broker_GenerarHistorico_FullMethodName = "/CyberDay.Broker/GenerarHistorico"
)

// BrokerClient is the client API for Broker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BrokerClient interface {
	GenerarOferta(ctx context.Context, in *Oferta, opts ...grpc.CallOption) (*Bool, error)
	Registrarse(ctx context.Context, in *Registro, opts ...grpc.CallOption) (*Bool, error)
	GenerarHistorico(ctx context.Context, in *Registro, opts ...grpc.CallOption) (*RangeSinceResponse, error)
}

type brokerClient struct {
	cc grpc.ClientConnInterface
}

func NewBrokerClient(cc grpc.ClientConnInterface) BrokerClient {
	return &brokerClient{cc}
}

func (c *brokerClient) GenerarOferta(ctx context.Context, in *Oferta, opts ...grpc.CallOption) (*Bool, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Bool)
	err := c.cc.Invoke(ctx, Broker_GenerarOferta_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerClient) Registrarse(ctx context.Context, in *Registro, opts ...grpc.CallOption) (*Bool, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Bool)
	err := c.cc.Invoke(ctx, Broker_Registrarse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerClient) GenerarHistorico(ctx context.Context, in *Registro, opts ...grpc.CallOption) (*RangeSinceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RangeSinceResponse)
	err := c.cc.Invoke(ctx, Broker_GenerarHistorico_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BrokerServer is the server API for Broker service.
// All implementations must embed UnimplementedBrokerServer
// for forward compatibility.
type BrokerServer interface {
	GenerarOferta(context.Context, *Oferta) (*Bool, error)
	Registrarse(context.Context, *Registro) (*Bool, error)
	GenerarHistorico(context.Context, *Registro) (*RangeSinceResponse, error)
	mustEmbedUnimplementedBrokerServer()
}

// UnimplementedBrokerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBrokerServer struct{}

func (UnimplementedBrokerServer) GenerarOferta(context.Context, *Oferta) (*Bool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerarOferta not implemented")
}
func (UnimplementedBrokerServer) Registrarse(context.Context, *Registro) (*Bool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Registrarse not implemented")
}
func (UnimplementedBrokerServer) GenerarHistorico(context.Context, *Registro) (*RangeSinceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerarHistorico not implemented")
}
func (UnimplementedBrokerServer) mustEmbedUnimplementedBrokerServer() {}
func (UnimplementedBrokerServer) testEmbeddedByValue()                {}

// UnsafeBrokerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BrokerServer will
// result in compilation errors.
type UnsafeBrokerServer interface {
	mustEmbedUnimplementedBrokerServer()
}

func RegisterBrokerServer(s grpc.ServiceRegistrar, srv BrokerServer) {
	// If the following call pancis, it indicates UnimplementedBrokerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Broker_ServiceDesc, srv)
}

func _Broker_GenerarOferta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Oferta)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServer).GenerarOferta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Broker_GenerarOferta_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServer).GenerarOferta(ctx, req.(*Oferta))
	}
	return interceptor(ctx, in, info, handler)
}

func _Broker_Registrarse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Registro)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServer).Registrarse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Broker_Registrarse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServer).Registrarse(ctx, req.(*Registro))
	}
	return interceptor(ctx, in, info, handler)
}

func _Broker_GenerarHistorico_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Registro)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServer).GenerarHistorico(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Broker_GenerarHistorico_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServer).GenerarHistorico(ctx, req.(*Registro))
	}
	return interceptor(ctx, in, info, handler)
}

// Broker_ServiceDesc is the grpc.ServiceDesc for Broker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Broker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "CyberDay.Broker",
	HandlerType: (*BrokerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerarOferta",
			Handler:    _Broker_GenerarOferta_Handler,
		},
		{
			MethodName: "Registrarse",
			Handler:    _Broker_Registrarse_Handler,
		},
		{
			MethodName: "GenerarHistorico",
			Handler:    _Broker_GenerarHistorico_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/proto.proto",
}

const (
	DBNode_Store_FullMethodName       = "/CyberDay.DBNode/Store"
	DBNode_Get_FullMethodName         = "/CyberDay.DBNode/Get"
	DBNode_RangeSince_FullMethodName  = "/CyberDay.DBNode/RangeSince"
	DBNode_GetHistoric_FullMethodName = "/CyberDay.DBNode/GetHistoric"
	DBNode_Siguesvivo_FullMethodName  = "/CyberDay.DBNode/siguesvivo"
)

// DBNodeClient is the client API for DBNode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DBNodeClient interface {
	Store(ctx context.Context, in *StoreRequest, opts ...grpc.CallOption) (*StoreResponse, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	RangeSince(ctx context.Context, in *RangeSinceRequest, opts ...grpc.CallOption) (*RangeSinceResponse, error)
	// agregada por mappo:
	GetHistoric(ctx context.Context, in *Filtro, opts ...grpc.CallOption) (*RangeSinceResponse, error)
	Siguesvivo(ctx context.Context, in *Vacio, opts ...grpc.CallOption) (*Bool, error)
}

type dBNodeClient struct {
	cc grpc.ClientConnInterface
}

func NewDBNodeClient(cc grpc.ClientConnInterface) DBNodeClient {
	return &dBNodeClient{cc}
}

func (c *dBNodeClient) Store(ctx context.Context, in *StoreRequest, opts ...grpc.CallOption) (*StoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreResponse)
	err := c.cc.Invoke(ctx, DBNode_Store_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBNodeClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, DBNode_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBNodeClient) RangeSince(ctx context.Context, in *RangeSinceRequest, opts ...grpc.CallOption) (*RangeSinceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RangeSinceResponse)
	err := c.cc.Invoke(ctx, DBNode_RangeSince_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBNodeClient) GetHistoric(ctx context.Context, in *Filtro, opts ...grpc.CallOption) (*RangeSinceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RangeSinceResponse)
	err := c.cc.Invoke(ctx, DBNode_GetHistoric_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBNodeClient) Siguesvivo(ctx context.Context, in *Vacio, opts ...grpc.CallOption) (*Bool, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Bool)
	err := c.cc.Invoke(ctx, DBNode_Siguesvivo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DBNodeServer is the server API for DBNode service.
// All implementations must embed UnimplementedDBNodeServer
// for forward compatibility.
type DBNodeServer interface {
	Store(context.Context, *StoreRequest) (*StoreResponse, error)
	Get(context.Context, *GetRequest) (*GetResponse, error)
	RangeSince(context.Context, *RangeSinceRequest) (*RangeSinceResponse, error)
	// agregada por mappo:
	GetHistoric(context.Context, *Filtro) (*RangeSinceResponse, error)
	Siguesvivo(context.Context, *Vacio) (*Bool, error)
	mustEmbedUnimplementedDBNodeServer()
}

// UnimplementedDBNodeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDBNodeServer struct{}

func (UnimplementedDBNodeServer) Store(context.Context, *StoreRequest) (*StoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Store not implemented")
}
func (UnimplementedDBNodeServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedDBNodeServer) RangeSince(context.Context, *RangeSinceRequest) (*RangeSinceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RangeSince not implemented")
}
func (UnimplementedDBNodeServer) GetHistoric(context.Context, *Filtro) (*RangeSinceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHistoric not implemented")
}
func (UnimplementedDBNodeServer) Siguesvivo(context.Context, *Vacio) (*Bool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Siguesvivo not implemented")
}
func (UnimplementedDBNodeServer) mustEmbedUnimplementedDBNodeServer() {}
func (UnimplementedDBNodeServer) testEmbeddedByValue()                {}

// UnsafeDBNodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DBNodeServer will
// result in compilation errors.
type UnsafeDBNodeServer interface {
	mustEmbedUnimplementedDBNodeServer()
}

func RegisterDBNodeServer(s grpc.ServiceRegistrar, srv DBNodeServer) {
	// If the following call pancis, it indicates UnimplementedDBNodeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DBNode_ServiceDesc, srv)
}

func _DBNode_Store_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBNodeServer).Store(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DBNode_Store_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBNodeServer).Store(ctx, req.(*StoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DBNode_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBNodeServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DBNode_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBNodeServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DBNode_RangeSince_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RangeSinceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBNodeServer).RangeSince(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DBNode_RangeSince_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBNodeServer).RangeSince(ctx, req.(*RangeSinceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DBNode_GetHistoric_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Filtro)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBNodeServer).GetHistoric(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DBNode_GetHistoric_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBNodeServer).GetHistoric(ctx, req.(*Filtro))
	}
	return interceptor(ctx, in, info, handler)
}

func _DBNode_Siguesvivo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Vacio)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBNodeServer).Siguesvivo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DBNode_Siguesvivo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBNodeServer).Siguesvivo(ctx, req.(*Vacio))
	}
	return interceptor(ctx, in, info, handler)
}

// DBNode_ServiceDesc is the grpc.ServiceDesc for DBNode service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DBNode_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "CyberDay.DBNode",
	HandlerType: (*DBNodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Store",
			Handler:    _DBNode_Store_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _DBNode_Get_Handler,
		},
		{
			MethodName: "RangeSince",
			Handler:    _DBNode_RangeSince_Handler,
		},
		{
			MethodName: "GetHistoric",
			Handler:    _DBNode_GetHistoric_Handler,
		},
		{
			MethodName: "siguesvivo",
			Handler:    _DBNode_Siguesvivo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/proto.proto",
}

const (
	Consumidor_NotificarOferta_FullMethodName = "/CyberDay.Consumidor/NotificarOferta"
	Consumidor_PedirDatos_FullMethodName      = "/CyberDay.Consumidor/pedirDatos"
)

// ConsumidorClient is the client API for Consumidor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConsumidorClient interface {
	NotificarOferta(ctx context.Context, in *Oferta, opts ...grpc.CallOption) (*Bool, error)
	PedirDatos(ctx context.Context, in *Vacio, opts ...grpc.CallOption) (*DatosFinalesConsumidor, error)
}

type consumidorClient struct {
	cc grpc.ClientConnInterface
}

func NewConsumidorClient(cc grpc.ClientConnInterface) ConsumidorClient {
	return &consumidorClient{cc}
}

func (c *consumidorClient) NotificarOferta(ctx context.Context, in *Oferta, opts ...grpc.CallOption) (*Bool, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Bool)
	err := c.cc.Invoke(ctx, Consumidor_NotificarOferta_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consumidorClient) PedirDatos(ctx context.Context, in *Vacio, opts ...grpc.CallOption) (*DatosFinalesConsumidor, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DatosFinalesConsumidor)
	err := c.cc.Invoke(ctx, Consumidor_PedirDatos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConsumidorServer is the server API for Consumidor service.
// All implementations must embed UnimplementedConsumidorServer
// for forward compatibility.
type ConsumidorServer interface {
	NotificarOferta(context.Context, *Oferta) (*Bool, error)
	PedirDatos(context.Context, *Vacio) (*DatosFinalesConsumidor, error)
	mustEmbedUnimplementedConsumidorServer()
}

// UnimplementedConsumidorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConsumidorServer struct{}

func (UnimplementedConsumidorServer) NotificarOferta(context.Context, *Oferta) (*Bool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotificarOferta not implemented")
}
func (UnimplementedConsumidorServer) PedirDatos(context.Context, *Vacio) (*DatosFinalesConsumidor, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PedirDatos not implemented")
}
func (UnimplementedConsumidorServer) mustEmbedUnimplementedConsumidorServer() {}
func (UnimplementedConsumidorServer) testEmbeddedByValue()                    {}

// UnsafeConsumidorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConsumidorServer will
// result in compilation errors.
type UnsafeConsumidorServer interface {
	mustEmbedUnimplementedConsumidorServer()
}

func RegisterConsumidorServer(s grpc.ServiceRegistrar, srv ConsumidorServer) {
	// If the following call pancis, it indicates UnimplementedConsumidorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Consumidor_ServiceDesc, srv)
}

func _Consumidor_NotificarOferta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Oferta)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsumidorServer).NotificarOferta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Consumidor_NotificarOferta_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsumidorServer).NotificarOferta(ctx, req.(*Oferta))
	}
	return interceptor(ctx, in, info, handler)
}

func _Consumidor_PedirDatos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Vacio)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsumidorServer).PedirDatos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Consumidor_PedirDatos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsumidorServer).PedirDatos(ctx, req.(*Vacio))
	}
	return interceptor(ctx, in, info, handler)
}

// Consumidor_ServiceDesc is the grpc.ServiceDesc for Consumidor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Consumidor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "CyberDay.Consumidor",
	HandlerType: (*ConsumidorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NotificarOferta",
			Handler:    _Consumidor_NotificarOferta_Handler,
		},
		{
			MethodName: "pedirDatos",
			Handler:    _Consumidor_PedirDatos_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/proto.proto",
}
