services:

  broker:
    build: ./broker
    container_name: broker
    ports:
      - "50050:50050"
    depends_on:
      - datanode0
      - datanode1
      - datanode2
    networks:
      - grpc-net
    volumes:
      - ./reporte:/app/reporte

  datanode2:
    build: ./datanodes
    container_name: datanode2
    environment:
      - ID=2
    networks:
      - grpc-net
    volumes:
      - ./datanodes/data2:/app/data2
    ports:
      - "50063:50063"

  cliente-ryw1:
    build: ./clienteRYW
    container_name: cliente-ryw1
    environment: 
      - CLIENT_ID=cliente-ryw_1
    depends_on:
      - coordinador
    networks:
      - grpc-net

  cliente-mr1:
    build: ./clienteMR
    container_name: cliente-mr1
    environment: 
      - CLIENT_ID=cliente-mr_1
    networks:
      - grpc-net
      
networks:
  grpc-net:
    driver: bridge