// se compila con:
// protoc --go_out=. --go-grpc_out=. .\prueba.proto
// crea la carpeta grpc-server

syntax = "proto3";

option go_package = "grpc-server/proto";
package Prueba;

service Prueba {
    rpc SolicitarOferta(OperationRequest) returns (OperationResponse) {}
    rpc AceptarOferta(Vacio) returns (Vacio) {}
}

message OperationRequest{
    string solicitud_oferta = 1;
}

message OperationResponse{
    optional string oferta = 1;
	optional double ExitoTrevor = 2;
	optional double ExitoFranklin = 3;
	optional double riesgo = 4;
	optional int64 botin = 5;
}

message Vacio{}