// se compila con:
// protoc --go_out=. --go-grpc_out=. .\lester.proto
// crea la carpeta grpc-server

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: lester.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Stars struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flag          bool                   `protobuf:"varint,1,opt,name=flag,proto3" json:"flag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stars) Reset() {
	*x = Stars{}
	mi := &file_lester_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stars) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stars) ProtoMessage() {}

func (x *Stars) ProtoReflect() protoreflect.Message {
	mi := &file_lester_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stars.ProtoReflect.Descriptor instead.
func (*Stars) Descriptor() ([]byte, []int) {
	return file_lester_proto_rawDescGZIP(), []int{0}
}

func (x *Stars) GetFlag() bool {
	if x != nil {
		return x.Flag
	}
	return false
}

type OperationRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SolicitudOferta string                 `protobuf:"bytes,1,opt,name=solicitud_oferta,json=solicitudOferta,proto3" json:"solicitud_oferta,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OperationRequest) Reset() {
	*x = OperationRequest{}
	mi := &file_lester_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationRequest) ProtoMessage() {}

func (x *OperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lester_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationRequest.ProtoReflect.Descriptor instead.
func (*OperationRequest) Descriptor() ([]byte, []int) {
	return file_lester_proto_rawDescGZIP(), []int{1}
}

func (x *OperationRequest) GetSolicitudOferta() string {
	if x != nil {
		return x.SolicitudOferta
	}
	return ""
}

type OperationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Oferta        *string                `protobuf:"bytes,1,opt,name=oferta,proto3,oneof" json:"oferta,omitempty"`
	ExitoTrevor   *int64                 `protobuf:"varint,2,opt,name=ExitoTrevor,proto3,oneof" json:"ExitoTrevor,omitempty"`
	ExitoFranklin *int64                 `protobuf:"varint,3,opt,name=ExitoFranklin,proto3,oneof" json:"ExitoFranklin,omitempty"`
	Riesgo        *int64                 `protobuf:"varint,4,opt,name=riesgo,proto3,oneof" json:"riesgo,omitempty"`
	Botin         *int64                 `protobuf:"varint,5,opt,name=botin,proto3,oneof" json:"botin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationResponse) Reset() {
	*x = OperationResponse{}
	mi := &file_lester_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationResponse) ProtoMessage() {}

func (x *OperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lester_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationResponse.ProtoReflect.Descriptor instead.
func (*OperationResponse) Descriptor() ([]byte, []int) {
	return file_lester_proto_rawDescGZIP(), []int{2}
}

func (x *OperationResponse) GetOferta() string {
	if x != nil && x.Oferta != nil {
		return *x.Oferta
	}
	return ""
}

func (x *OperationResponse) GetExitoTrevor() int64 {
	if x != nil && x.ExitoTrevor != nil {
		return *x.ExitoTrevor
	}
	return 0
}

func (x *OperationResponse) GetExitoFranklin() int64 {
	if x != nil && x.ExitoFranklin != nil {
		return *x.ExitoFranklin
	}
	return 0
}

func (x *OperationResponse) GetRiesgo() int64 {
	if x != nil && x.Riesgo != nil {
		return *x.Riesgo
	}
	return 0
}

func (x *OperationResponse) GetBotin() int64 {
	if x != nil && x.Botin != nil {
		return *x.Botin
	}
	return 0
}

type Pago struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BotinTotal    int64                  `protobuf:"varint,1,opt,name=BotinTotal,proto3" json:"BotinTotal,omitempty"`
	Pago          int64                  `protobuf:"varint,2,opt,name=Pago,proto3" json:"Pago,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pago) Reset() {
	*x = Pago{}
	mi := &file_lester_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pago) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pago) ProtoMessage() {}

func (x *Pago) ProtoReflect() protoreflect.Message {
	mi := &file_lester_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pago.ProtoReflect.Descriptor instead.
func (*Pago) Descriptor() ([]byte, []int) {
	return file_lester_proto_rawDescGZIP(), []int{3}
}

func (x *Pago) GetBotinTotal() int64 {
	if x != nil {
		return x.BotinTotal
	}
	return 0
}

func (x *Pago) GetPago() int64 {
	if x != nil {
		return x.Pago
	}
	return 0
}

type ConfirmacionPago struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Confirma      bool                   `protobuf:"varint,1,opt,name=Confirma,proto3" json:"Confirma,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmacionPago) Reset() {
	*x = ConfirmacionPago{}
	mi := &file_lester_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmacionPago) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmacionPago) ProtoMessage() {}

func (x *ConfirmacionPago) ProtoReflect() protoreflect.Message {
	mi := &file_lester_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmacionPago.ProtoReflect.Descriptor instead.
func (*ConfirmacionPago) Descriptor() ([]byte, []int) {
	return file_lester_proto_rawDescGZIP(), []int{4}
}

func (x *ConfirmacionPago) GetConfirma() bool {
	if x != nil {
		return x.Confirma
	}
	return false
}

type Vacio struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vacio) Reset() {
	*x = Vacio{}
	mi := &file_lester_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vacio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vacio) ProtoMessage() {}

func (x *Vacio) ProtoReflect() protoreflect.Message {
	mi := &file_lester_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vacio.ProtoReflect.Descriptor instead.
func (*Vacio) Descriptor() ([]byte, []int) {
	return file_lester_proto_rawDescGZIP(), []int{5}
}

var File_lester_proto protoreflect.FileDescriptor

const file_lester_proto_rawDesc = "" +
	"\n" +
	"\flester.proto\x12\x06Atraco\"\x1b\n" +
	"\x05Stars\x12\x12\n" +
	"\x04flag\x18\x01 \x01(\bR\x04flag\"=\n" +
	"\x10OperationRequest\x12)\n" +
	"\x10solicitud_oferta\x18\x01 \x01(\tR\x0fsolicitudOferta\"\xfc\x01\n" +
	"\x11OperationResponse\x12\x1b\n" +
	"\x06oferta\x18\x01 \x01(\tH\x00R\x06oferta\x88\x01\x01\x12%\n" +
	"\vExitoTrevor\x18\x02 \x01(\x03H\x01R\vExitoTrevor\x88\x01\x01\x12)\n" +
	"\rExitoFranklin\x18\x03 \x01(\x03H\x02R\rExitoFranklin\x88\x01\x01\x12\x1b\n" +
	"\x06riesgo\x18\x04 \x01(\x03H\x03R\x06riesgo\x88\x01\x01\x12\x19\n" +
	"\x05botin\x18\x05 \x01(\x03H\x04R\x05botin\x88\x01\x01B\t\n" +
	"\a_ofertaB\x0e\n" +
	"\f_ExitoTrevorB\x10\n" +
	"\x0e_ExitoFranklinB\t\n" +
	"\a_riesgoB\b\n" +
	"\x06_botin\":\n" +
	"\x04Pago\x12\x1e\n" +
	"\n" +
	"BotinTotal\x18\x01 \x01(\x03R\n" +
	"BotinTotal\x12\x12\n" +
	"\x04Pago\x18\x02 \x01(\x03R\x04Pago\".\n" +
	"\x10ConfirmacionPago\x12\x1a\n" +
	"\bConfirma\x18\x01 \x01(\bR\bConfirma\"\a\n" +
	"\x05Vacio2\x83\x01\n" +
	"\x06Prueba\x12H\n" +
	"\x0fSolicitarOferta\x12\x18.Atraco.OperationRequest\x1a\x19.Atraco.OperationResponse\"\x00\x12/\n" +
	"\rAceptarOferta\x12\r.Atraco.Vacio\x1a\r.Atraco.Vacio\"\x002|\n" +
	"\tEstrellas\x126\n" +
	"\x16EmpezarMandarEstrellas\x12\r.Atraco.Stars\x1a\r.Atraco.Stars\x127\n" +
	"\x17TerminarMandarEstrellas\x12\r.Atraco.Stars\x1a\r.Atraco.Stars2C\n" +
	"\tPagoBotin\x126\n" +
	"\n" +
	"EnviarPago\x12\f.Atraco.Pago\x1a\x18.Atraco.ConfirmacionPago\"\x00B\x13Z\x11grpc-server/protob\x06proto3"

var (
	file_lester_proto_rawDescOnce sync.Once
	file_lester_proto_rawDescData []byte
)

func file_lester_proto_rawDescGZIP() []byte {
	file_lester_proto_rawDescOnce.Do(func() {
		file_lester_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lester_proto_rawDesc), len(file_lester_proto_rawDesc)))
	})
	return file_lester_proto_rawDescData
}

var file_lester_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_lester_proto_goTypes = []any{
	(*Stars)(nil),             // 0: Atraco.Stars
	(*OperationRequest)(nil),  // 1: Atraco.OperationRequest
	(*OperationResponse)(nil), // 2: Atraco.OperationResponse
	(*Pago)(nil),              // 3: Atraco.Pago
	(*ConfirmacionPago)(nil),  // 4: Atraco.ConfirmacionPago
	(*Vacio)(nil),             // 5: Atraco.Vacio
}
var file_lester_proto_depIdxs = []int32{
	1, // 0: Atraco.Prueba.SolicitarOferta:input_type -> Atraco.OperationRequest
	5, // 1: Atraco.Prueba.AceptarOferta:input_type -> Atraco.Vacio
	0, // 2: Atraco.Estrellas.EmpezarMandarEstrellas:input_type -> Atraco.Stars
	0, // 3: Atraco.Estrellas.TerminarMandarEstrellas:input_type -> Atraco.Stars
	3, // 4: Atraco.PagoBotin.EnviarPago:input_type -> Atraco.Pago
	2, // 5: Atraco.Prueba.SolicitarOferta:output_type -> Atraco.OperationResponse
	5, // 6: Atraco.Prueba.AceptarOferta:output_type -> Atraco.Vacio
	0, // 7: Atraco.Estrellas.EmpezarMandarEstrellas:output_type -> Atraco.Stars
	0, // 8: Atraco.Estrellas.TerminarMandarEstrellas:output_type -> Atraco.Stars
	4, // 9: Atraco.PagoBotin.EnviarPago:output_type -> Atraco.ConfirmacionPago
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_lester_proto_init() }
func file_lester_proto_init() {
	if File_lester_proto != nil {
		return
	}
	file_lester_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lester_proto_rawDesc), len(file_lester_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_lester_proto_goTypes,
		DependencyIndexes: file_lester_proto_depIdxs,
		MessageInfos:      file_lester_proto_msgTypes,
	}.Build()
	File_lester_proto = out.File
	file_lester_proto_goTypes = nil
	file_lester_proto_depIdxs = nil
}
