// se compila con:
// protoc --go_out=. --go-grpc_out=. .\prueba.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: prueba.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OperationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operation     string                 `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationRequest) Reset() {
	*x = OperationRequest{}
	mi := &file_prueba_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationRequest) ProtoMessage() {}

func (x *OperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_prueba_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationRequest.ProtoReflect.Descriptor instead.
func (*OperationRequest) Descriptor() ([]byte, []int) {
	return file_prueba_proto_rawDescGZIP(), []int{0}
}

func (x *OperationRequest) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

type OperationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationResponse) Reset() {
	*x = OperationResponse{}
	mi := &file_prueba_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationResponse) ProtoMessage() {}

func (x *OperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_prueba_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationResponse.ProtoReflect.Descriptor instead.
func (*OperationResponse) Descriptor() ([]byte, []int) {
	return file_prueba_proto_rawDescGZIP(), []int{1}
}

func (x *OperationResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_prueba_proto protoreflect.FileDescriptor

const file_prueba_proto_rawDesc = "" +
	"\n" +
	"\fprueba.proto\x12\x06prueba\"0\n" +
	"\x10OperationRequest\x12\x1c\n" +
	"\toperation\x18\x01 \x01(\tR\toperation\"+\n" +
	"\x11OperationResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result2\x9b\x01\n" +
	"\x06prueba\x12F\n" +
	"\rSendOperation\x12\x18.prueba.OperationRequest\x1a\x19.prueba.OperationResponse\"\x00\x12I\n" +
	"\x10ProcessOperation\x12\x18.prueba.OperationRequest\x1a\x19.prueba.OperationResponse\"\x00B\x13Z\x11grpc-server/protob\x06proto3"

var (
	file_prueba_proto_rawDescOnce sync.Once
	file_prueba_proto_rawDescData []byte
)

func file_prueba_proto_rawDescGZIP() []byte {
	file_prueba_proto_rawDescOnce.Do(func() {
		file_prueba_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_prueba_proto_rawDesc), len(file_prueba_proto_rawDesc)))
	})
	return file_prueba_proto_rawDescData
}

var file_prueba_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_prueba_proto_goTypes = []any{
	(*OperationRequest)(nil),  // 0: prueba.OperationRequest
	(*OperationResponse)(nil), // 1: prueba.OperationResponse
}
var file_prueba_proto_depIdxs = []int32{
	0, // 0: prueba.prueba.SendOperation:input_type -> prueba.OperationRequest
	0, // 1: prueba.prueba.ProcessOperation:input_type -> prueba.OperationRequest
	1, // 2: prueba.prueba.SendOperation:output_type -> prueba.OperationResponse
	1, // 3: prueba.prueba.ProcessOperation:output_type -> prueba.OperationResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_prueba_proto_init() }
func file_prueba_proto_init() {
	if File_prueba_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_prueba_proto_rawDesc), len(file_prueba_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_prueba_proto_goTypes,
		DependencyIndexes: file_prueba_proto_depIdxs,
		MessageInfos:      file_prueba_proto_msgTypes,
	}.Build()
	File_prueba_proto = out.File
	file_prueba_proto_goTypes = nil
	file_prueba_proto_depIdxs = nil
}
