// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.32.0
// source: proto/proto.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	CoordinadorRYW_GetSeats_FullMethodName        = "/AeroDist.CoordinadorRYW/GetSeats"
	CoordinadorRYW_CheckIn_FullMethodName         = "/AeroDist.CoordinadorRYW/CheckIn"
	CoordinadorRYW_GetBoardingPass_FullMethodName = "/AeroDist.CoordinadorRYW/GetBoardingPass"
)

// CoordinadorRYWClient is the client API for CoordinadorRYW service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CoordinadorRYWClient interface {
	GetSeats(ctx context.Context, in *GetSeatsRequest, opts ...grpc.CallOption) (*GetSeatsResponse, error)
	CheckIn(ctx context.Context, in *CheckInRequest, opts ...grpc.CallOption) (*CheckInResponse, error)
	GetBoardingPass(ctx context.Context, in *GetBoardingPassRequest, opts ...grpc.CallOption) (*GetBoardingPassResponse, error)
}

type coordinadorRYWClient struct {
	cc grpc.ClientConnInterface
}

func NewCoordinadorRYWClient(cc grpc.ClientConnInterface) CoordinadorRYWClient {
	return &coordinadorRYWClient{cc}
}

func (c *coordinadorRYWClient) GetSeats(ctx context.Context, in *GetSeatsRequest, opts ...grpc.CallOption) (*GetSeatsResponse, error) {
	out := new(GetSeatsResponse)
	err := c.cc.Invoke(ctx, CoordinadorRYW_GetSeats_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinadorRYWClient) CheckIn(ctx context.Context, in *CheckInRequest, opts ...grpc.CallOption) (*CheckInResponse, error) {
	out := new(CheckInResponse)
	err := c.cc.Invoke(ctx, CoordinadorRYW_CheckIn_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinadorRYWClient) GetBoardingPass(ctx context.Context, in *GetBoardingPassRequest, opts ...grpc.CallOption) (*GetBoardingPassResponse, error) {
	out := new(GetBoardingPassResponse)
	err := c.cc.Invoke(ctx, CoordinadorRYW_GetBoardingPass_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoordinadorRYWServer is the server API for CoordinadorRYW service.
// All implementations must embed UnimplementedCoordinadorRYWServer
// for forward compatibility
type CoordinadorRYWServer interface {
	GetSeats(context.Context, *GetSeatsRequest) (*GetSeatsResponse, error)
	CheckIn(context.Context, *CheckInRequest) (*CheckInResponse, error)
	GetBoardingPass(context.Context, *GetBoardingPassRequest) (*GetBoardingPassResponse, error)
	mustEmbedUnimplementedCoordinadorRYWServer()
}

// UnimplementedCoordinadorRYWServer must be embedded to have forward compatible implementations.
type UnimplementedCoordinadorRYWServer struct {
}

func (UnimplementedCoordinadorRYWServer) GetSeats(context.Context, *GetSeatsRequest) (*GetSeatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSeats not implemented")
}
func (UnimplementedCoordinadorRYWServer) CheckIn(context.Context, *CheckInRequest) (*CheckInResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckIn not implemented")
}
func (UnimplementedCoordinadorRYWServer) GetBoardingPass(context.Context, *GetBoardingPassRequest) (*GetBoardingPassResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBoardingPass not implemented")
}
func (UnimplementedCoordinadorRYWServer) mustEmbedUnimplementedCoordinadorRYWServer() {}

// UnsafeCoordinadorRYWServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoordinadorRYWServer will
// result in compilation errors.
type UnsafeCoordinadorRYWServer interface {
	mustEmbedUnimplementedCoordinadorRYWServer()
}

func RegisterCoordinadorRYWServer(s grpc.ServiceRegistrar, srv CoordinadorRYWServer) {
	s.RegisterService(&CoordinadorRYW_ServiceDesc, srv)
}

func _CoordinadorRYW_GetSeats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSeatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinadorRYWServer).GetSeats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinadorRYW_GetSeats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinadorRYWServer).GetSeats(ctx, req.(*GetSeatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinadorRYW_CheckIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinadorRYWServer).CheckIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinadorRYW_CheckIn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinadorRYWServer).CheckIn(ctx, req.(*CheckInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinadorRYW_GetBoardingPass_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBoardingPassRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinadorRYWServer).GetBoardingPass(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinadorRYW_GetBoardingPass_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinadorRYWServer).GetBoardingPass(ctx, req.(*GetBoardingPassRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CoordinadorRYW_ServiceDesc is the grpc.ServiceDesc for CoordinadorRYW service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoordinadorRYW_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "AeroDist.CoordinadorRYW",
	HandlerType: (*CoordinadorRYWServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSeats",
			Handler:    _CoordinadorRYW_GetSeats_Handler,
		},
		{
			MethodName: "CheckIn",
			Handler:    _CoordinadorRYW_CheckIn_Handler,
		},
		{
			MethodName: "GetBoardingPass",
			Handler:    _CoordinadorRYW_GetBoardingPass_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/proto.proto",
}

const (
	Broker_GetInitialInfo_FullMethodName = "/AeroDist.Broker/GetInitialInfo"
	Broker_ApplyWrite_FullMethodName     = "/AeroDist.Broker/ApplyWrite"
	Broker_BrokerRead_FullMethodName     = "/AeroDist.Broker/BrokerRead"
)

// BrokerClient is the client API for Broker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BrokerClient interface {
	GetInitialInfo(ctx context.Context, in *GetInitialInfoRequest, opts ...grpc.CallOption) (*GetInitialInfoResponse, error)
	ApplyWrite(ctx context.Context, in *ApplyWriteRequest, opts ...grpc.CallOption) (*ApplyWriteResponse, error)
	BrokerRead(ctx context.Context, in *BrokerReadRequest, opts ...grpc.CallOption) (*BrokerReadResponse, error)
}

type brokerClient struct {
	cc grpc.ClientConnInterface
}

func NewBrokerClient(cc grpc.ClientConnInterface) BrokerClient {
	return &brokerClient{cc}
}

func (c *brokerClient) GetInitialInfo(ctx context.Context, in *GetInitialInfoRequest, opts ...grpc.CallOption) (*GetInitialInfoResponse, error) {
	out := new(GetInitialInfoResponse)
	err := c.cc.Invoke(ctx, Broker_GetInitialInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerClient) ApplyWrite(ctx context.Context, in *ApplyWriteRequest, opts ...grpc.CallOption) (*ApplyWriteResponse, error) {
	out := new(ApplyWriteResponse)
	err := c.cc.Invoke(ctx, Broker_ApplyWrite_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerClient) BrokerRead(ctx context.Context, in *BrokerReadRequest, opts ...grpc.CallOption) (*BrokerReadResponse, error) {
	out := new(BrokerReadResponse)
	err := c.cc.Invoke(ctx, Broker_BrokerRead_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BrokerServer is the server API for Broker service.
// All implementations must embed UnimplementedBrokerServer
// for forward compatibility
type BrokerServer interface {
	GetInitialInfo(context.Context, *GetInitialInfoRequest) (*GetInitialInfoResponse, error)
	ApplyWrite(context.Context, *ApplyWriteRequest) (*ApplyWriteResponse, error)
	BrokerRead(context.Context, *BrokerReadRequest) (*BrokerReadResponse, error)
	mustEmbedUnimplementedBrokerServer()
}

// UnimplementedBrokerServer must be embedded to have forward compatible implementations.
type UnimplementedBrokerServer struct {
}

func (UnimplementedBrokerServer) GetInitialInfo(context.Context, *GetInitialInfoRequest) (*GetInitialInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInitialInfo not implemented")
}
func (UnimplementedBrokerServer) ApplyWrite(context.Context, *ApplyWriteRequest) (*ApplyWriteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyWrite not implemented")
}
func (UnimplementedBrokerServer) BrokerRead(context.Context, *BrokerReadRequest) (*BrokerReadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BrokerRead not implemented")
}
func (UnimplementedBrokerServer) mustEmbedUnimplementedBrokerServer() {}

// UnsafeBrokerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BrokerServer will
// result in compilation errors.
type UnsafeBrokerServer interface {
	mustEmbedUnimplementedBrokerServer()
}

func RegisterBrokerServer(s grpc.ServiceRegistrar, srv BrokerServer) {
	s.RegisterService(&Broker_ServiceDesc, srv)
}

func _Broker_GetInitialInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInitialInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServer).GetInitialInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Broker_GetInitialInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServer).GetInitialInfo(ctx, req.(*GetInitialInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Broker_ApplyWrite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyWriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServer).ApplyWrite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Broker_ApplyWrite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServer).ApplyWrite(ctx, req.(*ApplyWriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Broker_BrokerRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BrokerReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServer).BrokerRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Broker_BrokerRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServer).BrokerRead(ctx, req.(*BrokerReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Broker_ServiceDesc is the grpc.ServiceDesc for Broker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Broker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "AeroDist.Broker",
	HandlerType: (*BrokerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInitialInfo",
			Handler:    _Broker_GetInitialInfo_Handler,
		},
		{
			MethodName: "ApplyWrite",
			Handler:    _Broker_ApplyWrite_Handler,
		},
		{
			MethodName: "BrokerRead",
			Handler:    _Broker_BrokerRead_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/proto.proto",
}
