syntax = "proto3";

package AeroDist;

option go_package = "/proto";

service CoordinadorRYW{//Servicio Coordinador con clientes RYW
    rpc GetSeats(GetSeatsRequest) returns (GetSeatsResponse);
    rpc CheckIn(CheckInRequest) returns (CheckInResponse);
    rpc GetBoardingPass(GetBoardingPassRequest) returns (GetBoardingPassResponse);
}

service Broker{
    rpc GetInitialInfo(GetInitialInfoRequest) returns (GetInitialInfoResponse);
    rpc ApplyWrite(ApplyWriteRequest) returns (ApplyWriteResponse);
    rpc BrokerRead(BrokerReadRequest) returns (BrokerReadResponse);
}


message CheckInRequest{
    string cliente_id = 1;
    string flight_id = 2;
    string seat = 3;
    string request_id = 4;
}

message CheckInResponse{
    bool success = 1;
    string msg = 2;
}

message GetBoardingPassRequest{
    string cliente_id = 1;
    string flight_id = 2;
}

message GetBoardingPassResponse{
    string flight_id = 1;
    string seat = 2;
    int64 version = 3;
    bool success = 4;
    string msg = 5;
}

message GetSeatsRequest{
    string flight_id = 1;
}

message GetSeatsResponse{
    string flight_id = 1;
    string seats = 2; //lista de asientos libres en el vuelo
    bool success = 3;
    string msg = 4;
}

message GetInitialInfoRequest{
    string flight_id = 1;
}

message GetInitialInfoResponse{
    string seats = 1;
    bool success = 2;
    string msg = 3;
}

message ApplyWriteRequest{
    string cliente_id = 1;
    string flight_id = 2;
    string seat = 3;
    string request_id = 4;
}

message ApplyWriteResponse{
    bool success = 1;
    string msg = 2;
    string datonode_id = 3;
    int64 version = 4;
}

message BrokerReadRequest{
    string flight_id = 1;
    string datanode_id = 2;
}

message BrokerReadResponse{
    string flight_id = 1;
    string seat = 2;
    string status = 3;
    string gate = 4;
    int64 version = 5;
    bool success = 6;
    string msg = 7;
}