

services:
  lester:
    build: ./Lester
    container_name: lester
    ports:
      - "50051:50051"  # expone el puerto del servidor
    networks:
      - grpc-net

  michael:
    build: ./Michael
    container_name: michael
    depends_on:
      - lester          # se asegura que el servidor esté arriba
    networks:
      - grpc-net
    environment:
      - SERVER_ADDR=lester:50051  # variable que tu cliente puede usar para conectarse

networks:
  grpc-net:
    driver: bridge