

services:
  lester:
    build: ./Lester
    container_name: lester
    depends_on:
      - rabbitmq
    ports:
      - "50051:50051"  # expone el puerto del servidor
    networks:
      - grpc-net
    environment:
      AMQP_URI: amqp://guest:guest@rabbitmq:5672/

  michael:
    build: ./Michael
    container_name: michael
    depends_on:
      - lester          # se asegura que el servidor esté arriba
      - trevor
      - franklin
    networks:
      - grpc-net
    environment:
      - SERVER_ADDR=lester:50051  # variable que tu cliente puede usar para conectarse

  trevor:
    build: ./Trevor
    container_name: trevor
    ports:
      - "50054:50054"
    networks:
      - grpc-net
    depends_on:
      - rabbitmq
    environment:
      AMQP_URI: amqp://guest:guest@rabbitmq:5672/
    
  franklin:
    build: ./Franklin
    container_name: franklin
    ports:
      - "50053:50053"
    networks:
      - grpc-net
    depends_on:
      - rabbitmq
    environment:
      AMQP_URI: amqp://guest:guest@rabbitmq:5672/

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # AMQP para tus servicios
      - "15672:15672"   # interfaz de administración web
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

networks:
  grpc-net:
    driver: bridge
