
services:
  broker:
    build: ./broker
    container_name: broker
    ports:
      - "50050:50050"
    networks:
      - grpc-net

  riploy:
    build: ./productores
    container_name: riploy
    environment:
      - NOMBRE_TIENDA=Riploy
      - CATALOGO=catalogos/riploy_catalogo.csv
    depends_on:
      - broker
    networks:
      - grpc-net
  
  falabellox:
    build: ./productores
    container_name: falabellox
    environment:
      - NOMBRE_TIENDA=Falabellox
      - CATALOGO=catalogos/falabellox_catalogo.csv
    depends_on:
      - broker
    networks:
      - grpc-net

  parisio:
    build: ./productores
    container_name: parisio
    environment:
      - NOMBRE_TIENDA=Parisio
      - CATALOGO=catalogos/parisio_catalogo.csv
    depends_on:
      - broker
    networks:
      - grpc-net

  grupo1:
    build: ./consumidores
    container_name: grupo1
    environment:
      - GRUPO=1
    depends_on:
      - broker
    networks:
      - grpc-net

  grupo2:
    build: ./consumidores
    container_name: grupo2
    environment:
      - GRUPO=2
    depends_on:
      - broker
    networks:
      - grpc-net
  grupo3:
    build: ./consumidores
    container_name: grupo3
    environment:
      - GRUPO=3
    depends_on:
      - broker
    networks:
      - grpc-net

  db1:
    build: ./db/Nodo1
    container_name: db1
    ports:
      - "50051:50051"
    environment:
      - NODE_ID=DB1
      - PORT=50051
      - DATA_PATH=/data/data.jsonl
    volumes:
      - ./db/Nodo1/data:/data
    networks:
      - grpc-net

  db2:
    build: ./db/Nodo2
    container_name: db2
    ports:
      - "50052:50052"
    environment:
      - NODE_ID=DB2
      - PORT=50051
      - DATA_PATH=/data/data.jsonl
    volumes:
      - ./db/Nodo2/data:/data
    networks:
      - grpc-net

  db3:
    build: ./db/Nodo3
    container_name: db3
    ports:
      - "50053:50053"
    environment:
      - NODE_ID=DB3
      - PORT=50051
      - DATA_PATH=/data/data.jsonl
    volumes:
      - ./db/Nodo3/data:/data
    networks:
      - grpc-net

networks:
  grpc-net:
    driver: bridge