// protoc --go_out=. --go-grpc_out=. proto/proto.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: proto/proto.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FligthStates struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlightId      string                 `protobuf:"bytes,1,opt,name=flight_id,json=flightId,proto3" json:"flight_id,omitempty"`
	UpdateType    string                 `protobuf:"bytes,2,opt,name=update_type,json=updateType,proto3" json:"update_type,omitempty"`
	UpdateValue   string                 `protobuf:"bytes,3,opt,name=update_value,json=updateValue,proto3" json:"update_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FligthStates) Reset() {
	*x = FligthStates{}
	mi := &file_proto_proto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FligthStates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FligthStates) ProtoMessage() {}

func (x *FligthStates) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FligthStates.ProtoReflect.Descriptor instead.
func (*FligthStates) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{0}
}

func (x *FligthStates) GetFlightId() string {
	if x != nil {
		return x.FlightId
	}
	return ""
}

func (x *FligthStates) GetUpdateType() string {
	if x != nil {
		return x.UpdateType
	}
	return ""
}

func (x *FligthStates) GetUpdateValue() string {
	if x != nil {
		return x.UpdateValue
	}
	return ""
}

type MRReadRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FlightId        string                 `protobuf:"bytes,1,opt,name=flight_id,json=flightId,proto3" json:"flight_id,omitempty"`
	ClientId        string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	LastVersionSeen int64                  `protobuf:"varint,3,opt,name=last_version_seen,json=lastVersionSeen,proto3" json:"last_version_seen,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MRReadRequest) Reset() {
	*x = MRReadRequest{}
	mi := &file_proto_proto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MRReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MRReadRequest) ProtoMessage() {}

func (x *MRReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MRReadRequest.ProtoReflect.Descriptor instead.
func (*MRReadRequest) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{1}
}

func (x *MRReadRequest) GetFlightId() string {
	if x != nil {
		return x.FlightId
	}
	return ""
}

func (x *MRReadRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *MRReadRequest) GetLastVersionSeen() int64 {
	if x != nil {
		return x.LastVersionSeen
	}
	return 0
}

type MRReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlightId      string                 `protobuf:"bytes,1,opt,name=flight_id,json=flightId,proto3" json:"flight_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Gate          string                 `protobuf:"bytes,3,opt,name=gate,proto3" json:"gate,omitempty"`
	Version       int64                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	Success       bool                   `protobuf:"varint,5,opt,name=success,proto3" json:"success,omitempty"`
	Msg           string                 `protobuf:"bytes,6,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MRReadResponse) Reset() {
	*x = MRReadResponse{}
	mi := &file_proto_proto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MRReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MRReadResponse) ProtoMessage() {}

func (x *MRReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MRReadResponse.ProtoReflect.Descriptor instead.
func (*MRReadResponse) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{2}
}

func (x *MRReadResponse) GetFlightId() string {
	if x != nil {
		return x.FlightId
	}
	return ""
}

func (x *MRReadResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MRReadResponse) GetGate() string {
	if x != nil {
		return x.Gate
	}
	return ""
}

func (x *MRReadResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *MRReadResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MRReadResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type Vacio struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vacio) Reset() {
	*x = Vacio{}
	mi := &file_proto_proto_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vacio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vacio) ProtoMessage() {}

func (x *Vacio) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vacio.ProtoReflect.Descriptor instead.
func (*Vacio) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{3}
}

var File_proto_proto_proto protoreflect.FileDescriptor

const file_proto_proto_proto_rawDesc = "" +
	"\n" +
	"\x11proto/proto.proto\x12\bAeroDist\"o\n" +
	"\fFligthStates\x12\x1b\n" +
	"\tflight_id\x18\x01 \x01(\tR\bflightId\x12\x1f\n" +
	"\vupdate_type\x18\x02 \x01(\tR\n" +
	"updateType\x12!\n" +
	"\fupdate_value\x18\x03 \x01(\tR\vupdateValue\"u\n" +
	"\rMRReadRequest\x12\x1b\n" +
	"\tflight_id\x18\x01 \x01(\tR\bflightId\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12*\n" +
	"\x11last_version_seen\x18\x03 \x01(\x03R\x0flastVersionSeen\"\x9f\x01\n" +
	"\x0eMRReadResponse\x12\x1b\n" +
	"\tflight_id\x18\x01 \x01(\tR\bflightId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x12\n" +
	"\x04gate\x18\x03 \x01(\tR\x04gate\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x03R\aversion\x12\x18\n" +
	"\asuccess\x18\x05 \x01(\bR\asuccess\x12\x10\n" +
	"\x03msg\x18\x06 \x01(\tR\x03msg\"\a\n" +
	"\x05Vacio2\x80\x01\n" +
	"\bDatanode\x127\n" +
	"\fFligthUpdate\x12\x16.AeroDist.FligthStates\x1a\x0f.AeroDist.Vacio\x12;\n" +
	"\x06MRRead\x12\x17.AeroDist.MRReadRequest\x1a\x18.AeroDist.MRReadResponseB\bZ\x06/protob\x06proto3"

var (
	file_proto_proto_proto_rawDescOnce sync.Once
	file_proto_proto_proto_rawDescData []byte
)

func file_proto_proto_proto_rawDescGZIP() []byte {
	file_proto_proto_proto_rawDescOnce.Do(func() {
		file_proto_proto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_proto_proto_rawDesc), len(file_proto_proto_proto_rawDesc)))
	})
	return file_proto_proto_proto_rawDescData
}

var file_proto_proto_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_proto_proto_goTypes = []any{
	(*FligthStates)(nil),   // 0: AeroDist.FligthStates
	(*MRReadRequest)(nil),  // 1: AeroDist.MRReadRequest
	(*MRReadResponse)(nil), // 2: AeroDist.MRReadResponse
	(*Vacio)(nil),          // 3: AeroDist.Vacio
}
var file_proto_proto_proto_depIdxs = []int32{
	0, // 0: AeroDist.Datanode.FligthUpdate:input_type -> AeroDist.FligthStates
	1, // 1: AeroDist.Datanode.MRRead:input_type -> AeroDist.MRReadRequest
	3, // 2: AeroDist.Datanode.FligthUpdate:output_type -> AeroDist.Vacio
	2, // 3: AeroDist.Datanode.MRRead:output_type -> AeroDist.MRReadResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_proto_proto_init() }
func file_proto_proto_proto_init() {
	if File_proto_proto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_proto_proto_rawDesc), len(file_proto_proto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_proto_proto_goTypes,
		DependencyIndexes: file_proto_proto_proto_depIdxs,
		MessageInfos:      file_proto_proto_proto_msgTypes,
	}.Build()
	File_proto_proto_proto = out.File
	file_proto_proto_proto_goTypes = nil
	file_proto_proto_proto_depIdxs = nil
}
