// protoc --go_out=. --go-grpc_out=. proto/proto.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: proto/proto.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Datanode_FligthUpdate_FullMethodName    = "/AeroDist.Datanode/FligthUpdate"
	Datanode_MRRead_FullMethodName          = "/AeroDist.Datanode/MRRead"
	Datanode_CompararRelojes_FullMethodName = "/AeroDist.Datanode/CompararRelojes"
)

// DatanodeClient is the client API for Datanode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DatanodeClient interface {
	// Broker
	FligthUpdate(ctx context.Context, in *FligthStates, opts ...grpc.CallOption) (*Vacio, error)
	// Clientes MR
	MRRead(ctx context.Context, in *MRReadRequest, opts ...grpc.CallOption) (*MRReadResponse, error)
	// solo para datanodes:
	CompararRelojes(ctx context.Context, in *Data, opts ...grpc.CallOption) (*Data, error)
}

type datanodeClient struct {
	cc grpc.ClientConnInterface
}

func NewDatanodeClient(cc grpc.ClientConnInterface) DatanodeClient {
	return &datanodeClient{cc}
}

func (c *datanodeClient) FligthUpdate(ctx context.Context, in *FligthStates, opts ...grpc.CallOption) (*Vacio, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Vacio)
	err := c.cc.Invoke(ctx, Datanode_FligthUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datanodeClient) MRRead(ctx context.Context, in *MRReadRequest, opts ...grpc.CallOption) (*MRReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MRReadResponse)
	err := c.cc.Invoke(ctx, Datanode_MRRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datanodeClient) CompararRelojes(ctx context.Context, in *Data, opts ...grpc.CallOption) (*Data, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Data)
	err := c.cc.Invoke(ctx, Datanode_CompararRelojes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DatanodeServer is the server API for Datanode service.
// All implementations must embed UnimplementedDatanodeServer
// for forward compatibility.
type DatanodeServer interface {
	// Broker
	FligthUpdate(context.Context, *FligthStates) (*Vacio, error)
	// Clientes MR
	MRRead(context.Context, *MRReadRequest) (*MRReadResponse, error)
	// solo para datanodes:
	CompararRelojes(context.Context, *Data) (*Data, error)
	mustEmbedUnimplementedDatanodeServer()
}

// UnimplementedDatanodeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDatanodeServer struct{}

func (UnimplementedDatanodeServer) FligthUpdate(context.Context, *FligthStates) (*Vacio, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FligthUpdate not implemented")
}
func (UnimplementedDatanodeServer) MRRead(context.Context, *MRReadRequest) (*MRReadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MRRead not implemented")
}
func (UnimplementedDatanodeServer) CompararRelojes(context.Context, *Data) (*Data, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompararRelojes not implemented")
}
func (UnimplementedDatanodeServer) mustEmbedUnimplementedDatanodeServer() {}
func (UnimplementedDatanodeServer) testEmbeddedByValue()                  {}

// UnsafeDatanodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DatanodeServer will
// result in compilation errors.
type UnsafeDatanodeServer interface {
	mustEmbedUnimplementedDatanodeServer()
}

func RegisterDatanodeServer(s grpc.ServiceRegistrar, srv DatanodeServer) {
	// If the following call pancis, it indicates UnimplementedDatanodeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Datanode_ServiceDesc, srv)
}

func _Datanode_FligthUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FligthStates)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatanodeServer).FligthUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Datanode_FligthUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatanodeServer).FligthUpdate(ctx, req.(*FligthStates))
	}
	return interceptor(ctx, in, info, handler)
}

func _Datanode_MRRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MRReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatanodeServer).MRRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Datanode_MRRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatanodeServer).MRRead(ctx, req.(*MRReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Datanode_CompararRelojes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Data)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatanodeServer).CompararRelojes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Datanode_CompararRelojes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatanodeServer).CompararRelojes(ctx, req.(*Data))
	}
	return interceptor(ctx, in, info, handler)
}

// Datanode_ServiceDesc is the grpc.ServiceDesc for Datanode service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Datanode_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "AeroDist.Datanode",
	HandlerType: (*DatanodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FligthUpdate",
			Handler:    _Datanode_FligthUpdate_Handler,
		},
		{
			MethodName: "MRRead",
			Handler:    _Datanode_MRRead_Handler,
		},
		{
			MethodName: "CompararRelojes",
			Handler:    _Datanode_CompararRelojes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/proto.proto",
}
