// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.32.0
// source: proto/proto.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	BrokerMR_MRRead_FullMethodName = "/AeroDist.BrokerMR/MRRead"
)

// BrokerMRClient is the client API for BrokerMR service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BrokerMRClient interface {
	MRRead(ctx context.Context, in *MRReadRequest, opts ...grpc.CallOption) (*MRReadResponse, error)
}

type brokerMRClient struct {
	cc grpc.ClientConnInterface
}

func NewBrokerMRClient(cc grpc.ClientConnInterface) BrokerMRClient {
	return &brokerMRClient{cc}
}

func (c *brokerMRClient) MRRead(ctx context.Context, in *MRReadRequest, opts ...grpc.CallOption) (*MRReadResponse, error) {
	out := new(MRReadResponse)
	err := c.cc.Invoke(ctx, BrokerMR_MRRead_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BrokerMRServer is the server API for BrokerMR service.
// All implementations must embed UnimplementedBrokerMRServer
// for forward compatibility
type BrokerMRServer interface {
	MRRead(context.Context, *MRReadRequest) (*MRReadResponse, error)
	mustEmbedUnimplementedBrokerMRServer()
}

// UnimplementedBrokerMRServer must be embedded to have forward compatible implementations.
type UnimplementedBrokerMRServer struct {
}

func (UnimplementedBrokerMRServer) MRRead(context.Context, *MRReadRequest) (*MRReadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MRRead not implemented")
}
func (UnimplementedBrokerMRServer) mustEmbedUnimplementedBrokerMRServer() {}

// UnsafeBrokerMRServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BrokerMRServer will
// result in compilation errors.
type UnsafeBrokerMRServer interface {
	mustEmbedUnimplementedBrokerMRServer()
}

func RegisterBrokerMRServer(s grpc.ServiceRegistrar, srv BrokerMRServer) {
	s.RegisterService(&BrokerMR_ServiceDesc, srv)
}

func _BrokerMR_MRRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MRReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerMRServer).MRRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrokerMR_MRRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerMRServer).MRRead(ctx, req.(*MRReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BrokerMR_ServiceDesc is the grpc.ServiceDesc for BrokerMR service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BrokerMR_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "AeroDist.BrokerMR",
	HandlerType: (*BrokerMRServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MRRead",
			Handler:    _BrokerMR_MRRead_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/proto.proto",
}
