services:

  #broker:
  #  build: ./broker
  #  container_name: broker
  #  ports:
  #    - "50050:50050"

  # Nodos consenso:
  dbatc0:
    build: ./dbatc
    container_name: dbatc0
    environment:
      - ID=0
    #depends_on:
    #  - broker
    networks:
      - grpc-net
    volumes:
      - ./dbATC/data0:/app/data0
    ports:
      - "50051:50051"
  
  dbatc1:
    build: ./dbatc
    container_name: dbatc1
    environment:
      - ID=1
    #depends_on:
    #  - broker
    networks:
      - grpc-net
    volumes:
      - ./dbATC/data1:/app/data1
    ports:
      - "50052:50052"


  dbatc2:
    build: ./dbatc
    container_name: dbatc2
    environment:
      - ID=2
    #depends_on:
    #  - broker
    networks:
      - grpc-net
    volumes:
      - ./dbATC/data2:/app/data2
    ports:
      - "50053:50053"

  datanode0:
    build: ./datanodes
    container_name: datanode0
    environment:
      - ID=0
    #depends_on:
    #  - broker
    networks:
      - grpc-net
    volumes:
      - ./datanodes/data0:/app/data0
    ports:
      - "50061:50061"

  datanode1:
    build: ./datanodes
    container_name: datanode1
    environment:
      - ID=1
    #depends_on:
    #  - broker
    networks:
      - grpc-net
    volumes:
      - ./datanodes/data0:/app/data1
    ports:
      - "50062:50062"
  
  datanode2:
    build: ./datanodes
    container_name: datanode2
    environment:
      - ID=2
    #depends_on:
    #  - broker
    networks:
      - grpc-net
    volumes:
      - ./datanodes/data2:/app/data2
    ports:
      - "50063:50063"

  coordinador:
    build: ./coordinador
    container_name: coordinador
    ports:
      - "50060:50060"
    #depends_on:
    #  - broker
    networks:
      - grpc-net

  clienteryw1:
    build: ./clienteRYW
    container_name: clienteRYW1
    environment: 
      - CLIENT_ID=clienteRYW_1
    depends_on:
      - coordinador
    networks:
      - grpc-net
  
  clienteryw2:
    build: ./clienteRYW
    container_name: clienteRYW2
    environment: 
      - CLIENT_ID=clienteRYW_2
    depends_on:
      - coordinador
    networks:
      - grpc-net
    
  clienteryw3:
    build: ./clienteRYW
    container_name: clienteRYW3
    environment: 
      - CLIENT_ID=clienteRYW_3
    depends_on:
      - coordinador
    networks:
      - grpc-net

  clientemr1:
    build: ./clienteMR
    container_name: clienteMR1
    environment: 
      - CLIENT_ID=clienteMR_1
    #depends_on:
    #  - broker
    networks:
      - grpc-net

  clientemr2:
    build: ./clienteMR
    container_name: clienteMR2
    environment: 
      - CLIENT_ID=clienteMR_2
    #depends_on:
    #  - broker
    networks:
      - grpc-net
      
networks:
  grpc-net:
    driver: bridge