// se compila con:
// protoc --go_out=. --go-grpc_out=. .\michael.proto
// crea la carpeta grpc-server

syntax = "proto3";

option go_package = "grpc-server/proto";
package Atraco;

service Prueba {
    rpc SolicitarOferta(OperationRequest) returns (OperationResponse) {}
    rpc AceptarOferta(Vacio) returns (Vacio) {}
}

service Distraccion {
    rpc InicioDistraccion(Instruccion) returns (ResultadoDistraccion) {}
}

service Golpe {
    rpc InicioGolpe(Instruccion) returns (ResultadoGolpe) {}
}


service Estrellas {
    rpc EmpezarMandarEstrellas(Stars) returns (Stars);
    rpc TerminarMandarEstrellas(Stars) returns (Stars);
}

service PagoBotin{
    rpc EnviarPago(Pago) returns (ConfirmacionPago) {}
}

message Stars{
    bool flag = 1;
}

message ResultadoGolpe{
    bool ExitoGolpe = 1;
    int64 BotinExtra = 3;
}

message Instruccion{
    int64 numTurnos = 1;
}

message ResultadoDistraccion{
    string ExitoDistraccion = 1;
    bool exito = 2;
}

message OperationRequest{
    string solicitud_oferta = 1;
}

message OperationResponse{
    optional string oferta = 1;
	optional int64 ExitoTrevor = 2;
	optional int64 ExitoFranklin = 3;
	optional int64 riesgo = 4;
	optional int64 botin = 5;
}

message Pago{
    int64 BotinTotal = 1;
    int64 Pago = 2;
}

message ConfirmacionPago{
    bool Confirma = 1;
}

message Vacio{}