
syntax = "proto3";

option go_package = "grpc-server/proto";
package Prueba;

service Prueba {
    rpc SolicitarOferta(OperationRequest) returns (OperationResponse) {}
    rpc AceptarOferta(Vacio) returns (Vacio) {}
}

service Distraccion {
    rpc InicioDistraccion(Instruccion) returns (Resultado) {}
}

message Instruccion{
    int64 numTurnos = 1;
}

message Resultado{
    string ExitoDistraccion = 1;
    bool exito = 2;
}

message OperationRequest{
    string solicitud_oferta = 1;
}

message OperationResponse{
    string oferta = 1;
	double ExitoTrevor = 2;
	double ExitoFranklin = 3;
	double riesgo = 4;
	int64 botin = 5;
}

message Vacio{}