// se compila con:
// protoc --go_out=. --go-grpc_out=. .\lester.proto
// crea la carpeta grpc-server

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.32.0
// source: lester.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Prueba_SolicitarOferta_FullMethodName = "/Atraco.Prueba/SolicitarOferta"
	Prueba_AceptarOferta_FullMethodName   = "/Atraco.Prueba/AceptarOferta"
)

// PruebaClient is the client API for Prueba service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PruebaClient interface {
	SolicitarOferta(ctx context.Context, in *OperationRequest, opts ...grpc.CallOption) (*OperationResponse, error)
	AceptarOferta(ctx context.Context, in *Vacio, opts ...grpc.CallOption) (*Vacio, error)
}

type pruebaClient struct {
	cc grpc.ClientConnInterface
}

func NewPruebaClient(cc grpc.ClientConnInterface) PruebaClient {
	return &pruebaClient{cc}
}

func (c *pruebaClient) SolicitarOferta(ctx context.Context, in *OperationRequest, opts ...grpc.CallOption) (*OperationResponse, error) {
	out := new(OperationResponse)
	err := c.cc.Invoke(ctx, Prueba_SolicitarOferta_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pruebaClient) AceptarOferta(ctx context.Context, in *Vacio, opts ...grpc.CallOption) (*Vacio, error) {
	out := new(Vacio)
	err := c.cc.Invoke(ctx, Prueba_AceptarOferta_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PruebaServer is the server API for Prueba service.
// All implementations must embed UnimplementedPruebaServer
// for forward compatibility
type PruebaServer interface {
	SolicitarOferta(context.Context, *OperationRequest) (*OperationResponse, error)
	AceptarOferta(context.Context, *Vacio) (*Vacio, error)
	mustEmbedUnimplementedPruebaServer()
}

// UnimplementedPruebaServer must be embedded to have forward compatible implementations.
type UnimplementedPruebaServer struct {
}

func (UnimplementedPruebaServer) SolicitarOferta(context.Context, *OperationRequest) (*OperationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SolicitarOferta not implemented")
}
func (UnimplementedPruebaServer) AceptarOferta(context.Context, *Vacio) (*Vacio, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AceptarOferta not implemented")
}
func (UnimplementedPruebaServer) mustEmbedUnimplementedPruebaServer() {}

// UnsafePruebaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PruebaServer will
// result in compilation errors.
type UnsafePruebaServer interface {
	mustEmbedUnimplementedPruebaServer()
}

func RegisterPruebaServer(s grpc.ServiceRegistrar, srv PruebaServer) {
	s.RegisterService(&Prueba_ServiceDesc, srv)
}

func _Prueba_SolicitarOferta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PruebaServer).SolicitarOferta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Prueba_SolicitarOferta_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PruebaServer).SolicitarOferta(ctx, req.(*OperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Prueba_AceptarOferta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Vacio)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PruebaServer).AceptarOferta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Prueba_AceptarOferta_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PruebaServer).AceptarOferta(ctx, req.(*Vacio))
	}
	return interceptor(ctx, in, info, handler)
}

// Prueba_ServiceDesc is the grpc.ServiceDesc for Prueba service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Prueba_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Atraco.Prueba",
	HandlerType: (*PruebaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SolicitarOferta",
			Handler:    _Prueba_SolicitarOferta_Handler,
		},
		{
			MethodName: "AceptarOferta",
			Handler:    _Prueba_AceptarOferta_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lester.proto",
}

const (
	Estrellas_EmpezarMandarEstrellas_FullMethodName  = "/Atraco.Estrellas/EmpezarMandarEstrellas"
	Estrellas_TerminarMandarEstrellas_FullMethodName = "/Atraco.Estrellas/TerminarMandarEstrellas"
)

// EstrellasClient is the client API for Estrellas service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EstrellasClient interface {
	EmpezarMandarEstrellas(ctx context.Context, in *Stars, opts ...grpc.CallOption) (*Stars, error)
	TerminarMandarEstrellas(ctx context.Context, in *Stars, opts ...grpc.CallOption) (*Stars, error)
}

type estrellasClient struct {
	cc grpc.ClientConnInterface
}

func NewEstrellasClient(cc grpc.ClientConnInterface) EstrellasClient {
	return &estrellasClient{cc}
}

func (c *estrellasClient) EmpezarMandarEstrellas(ctx context.Context, in *Stars, opts ...grpc.CallOption) (*Stars, error) {
	out := new(Stars)
	err := c.cc.Invoke(ctx, Estrellas_EmpezarMandarEstrellas_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *estrellasClient) TerminarMandarEstrellas(ctx context.Context, in *Stars, opts ...grpc.CallOption) (*Stars, error) {
	out := new(Stars)
	err := c.cc.Invoke(ctx, Estrellas_TerminarMandarEstrellas_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EstrellasServer is the server API for Estrellas service.
// All implementations must embed UnimplementedEstrellasServer
// for forward compatibility
type EstrellasServer interface {
	EmpezarMandarEstrellas(context.Context, *Stars) (*Stars, error)
	TerminarMandarEstrellas(context.Context, *Stars) (*Stars, error)
	mustEmbedUnimplementedEstrellasServer()
}

// UnimplementedEstrellasServer must be embedded to have forward compatible implementations.
type UnimplementedEstrellasServer struct {
}

func (UnimplementedEstrellasServer) EmpezarMandarEstrellas(context.Context, *Stars) (*Stars, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EmpezarMandarEstrellas not implemented")
}
func (UnimplementedEstrellasServer) TerminarMandarEstrellas(context.Context, *Stars) (*Stars, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TerminarMandarEstrellas not implemented")
}
func (UnimplementedEstrellasServer) mustEmbedUnimplementedEstrellasServer() {}

// UnsafeEstrellasServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EstrellasServer will
// result in compilation errors.
type UnsafeEstrellasServer interface {
	mustEmbedUnimplementedEstrellasServer()
}

func RegisterEstrellasServer(s grpc.ServiceRegistrar, srv EstrellasServer) {
	s.RegisterService(&Estrellas_ServiceDesc, srv)
}

func _Estrellas_EmpezarMandarEstrellas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Stars)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EstrellasServer).EmpezarMandarEstrellas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Estrellas_EmpezarMandarEstrellas_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EstrellasServer).EmpezarMandarEstrellas(ctx, req.(*Stars))
	}
	return interceptor(ctx, in, info, handler)
}

func _Estrellas_TerminarMandarEstrellas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Stars)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EstrellasServer).TerminarMandarEstrellas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Estrellas_TerminarMandarEstrellas_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EstrellasServer).TerminarMandarEstrellas(ctx, req.(*Stars))
	}
	return interceptor(ctx, in, info, handler)
}

// Estrellas_ServiceDesc is the grpc.ServiceDesc for Estrellas service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Estrellas_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Atraco.Estrellas",
	HandlerType: (*EstrellasServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EmpezarMandarEstrellas",
			Handler:    _Estrellas_EmpezarMandarEstrellas_Handler,
		},
		{
			MethodName: "TerminarMandarEstrellas",
			Handler:    _Estrellas_TerminarMandarEstrellas_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lester.proto",
}

const (
	PagoBotin_ConfirmarPago_FullMethodName = "/Atraco.PagoBotin/ConfirmarPago"
)

// PagoBotinClient is the client API for PagoBotin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PagoBotinClient interface {
	ConfirmarPago(ctx context.Context, in *Pago, opts ...grpc.CallOption) (*ConfirmacionPago, error)
}

type pagoBotinClient struct {
	cc grpc.ClientConnInterface
}

func NewPagoBotinClient(cc grpc.ClientConnInterface) PagoBotinClient {
	return &pagoBotinClient{cc}
}

func (c *pagoBotinClient) ConfirmarPago(ctx context.Context, in *Pago, opts ...grpc.CallOption) (*ConfirmacionPago, error) {
	out := new(ConfirmacionPago)
	err := c.cc.Invoke(ctx, PagoBotin_ConfirmarPago_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PagoBotinServer is the server API for PagoBotin service.
// All implementations must embed UnimplementedPagoBotinServer
// for forward compatibility
type PagoBotinServer interface {
	ConfirmarPago(context.Context, *Pago) (*ConfirmacionPago, error)
	mustEmbedUnimplementedPagoBotinServer()
}

// UnimplementedPagoBotinServer must be embedded to have forward compatible implementations.
type UnimplementedPagoBotinServer struct {
}

func (UnimplementedPagoBotinServer) ConfirmarPago(context.Context, *Pago) (*ConfirmacionPago, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmarPago not implemented")
}
func (UnimplementedPagoBotinServer) mustEmbedUnimplementedPagoBotinServer() {}

// UnsafePagoBotinServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PagoBotinServer will
// result in compilation errors.
type UnsafePagoBotinServer interface {
	mustEmbedUnimplementedPagoBotinServer()
}

func RegisterPagoBotinServer(s grpc.ServiceRegistrar, srv PagoBotinServer) {
	s.RegisterService(&PagoBotin_ServiceDesc, srv)
}

func _PagoBotin_ConfirmarPago_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Pago)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PagoBotinServer).ConfirmarPago(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PagoBotin_ConfirmarPago_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PagoBotinServer).ConfirmarPago(ctx, req.(*Pago))
	}
	return interceptor(ctx, in, info, handler)
}

// PagoBotin_ServiceDesc is the grpc.ServiceDesc for PagoBotin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PagoBotin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Atraco.PagoBotin",
	HandlerType: (*PagoBotinServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConfirmarPago",
			Handler:    _PagoBotin_ConfirmarPago_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lester.proto",
}
