// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v6.32.0
// source: trevor.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Instruccion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NumTurnos int64 `protobuf:"varint,1,opt,name=numTurnos,proto3" json:"numTurnos,omitempty"`
}

func (x *Instruccion) Reset() {
	*x = Instruccion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trevor_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Instruccion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Instruccion) ProtoMessage() {}

func (x *Instruccion) ProtoReflect() protoreflect.Message {
	mi := &file_trevor_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Instruccion.ProtoReflect.Descriptor instead.
func (*Instruccion) Descriptor() ([]byte, []int) {
	return file_trevor_proto_rawDescGZIP(), []int{0}
}

func (x *Instruccion) GetNumTurnos() int64 {
	if x != nil {
		return x.NumTurnos
	}
	return 0
}

type ResultadoDistraccion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ExitoDistraccion string `protobuf:"bytes,1,opt,name=ExitoDistraccion,proto3" json:"ExitoDistraccion,omitempty"`
	Exito            bool   `protobuf:"varint,2,opt,name=exito,proto3" json:"exito,omitempty"`
}

func (x *ResultadoDistraccion) Reset() {
	*x = ResultadoDistraccion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trevor_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResultadoDistraccion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultadoDistraccion) ProtoMessage() {}

func (x *ResultadoDistraccion) ProtoReflect() protoreflect.Message {
	mi := &file_trevor_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultadoDistraccion.ProtoReflect.Descriptor instead.
func (*ResultadoDistraccion) Descriptor() ([]byte, []int) {
	return file_trevor_proto_rawDescGZIP(), []int{1}
}

func (x *ResultadoDistraccion) GetExitoDistraccion() string {
	if x != nil {
		return x.ExitoDistraccion
	}
	return ""
}

func (x *ResultadoDistraccion) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

type ResultadoGolpe struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ExitoGolpe bool  `protobuf:"varint,1,opt,name=ExitoGolpe,proto3" json:"ExitoGolpe,omitempty"`
	BotinExtra int64 `protobuf:"varint,3,opt,name=BotinExtra,proto3" json:"BotinExtra,omitempty"`
}

func (x *ResultadoGolpe) Reset() {
	*x = ResultadoGolpe{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trevor_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResultadoGolpe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultadoGolpe) ProtoMessage() {}

func (x *ResultadoGolpe) ProtoReflect() protoreflect.Message {
	mi := &file_trevor_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultadoGolpe.ProtoReflect.Descriptor instead.
func (*ResultadoGolpe) Descriptor() ([]byte, []int) {
	return file_trevor_proto_rawDescGZIP(), []int{2}
}

func (x *ResultadoGolpe) GetExitoGolpe() bool {
	if x != nil {
		return x.ExitoGolpe
	}
	return false
}

func (x *ResultadoGolpe) GetBotinExtra() int64 {
	if x != nil {
		return x.BotinExtra
	}
	return 0
}

type Vacio struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Vacio) Reset() {
	*x = Vacio{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trevor_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Vacio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vacio) ProtoMessage() {}

func (x *Vacio) ProtoReflect() protoreflect.Message {
	mi := &file_trevor_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vacio.ProtoReflect.Descriptor instead.
func (*Vacio) Descriptor() ([]byte, []int) {
	return file_trevor_proto_rawDescGZIP(), []int{3}
}

var File_trevor_proto protoreflect.FileDescriptor

var file_trevor_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x74, 0x72, 0x65, 0x76, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x41, 0x74, 0x72, 0x61, 0x63, 0x6f, 0x22, 0x2b, 0x0a, 0x0b, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x75,
	0x63, 0x63, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x75, 0x6d, 0x54, 0x75, 0x72, 0x6e,
	0x6f, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x6e, 0x75, 0x6d, 0x54, 0x75, 0x72,
	0x6e, 0x6f, 0x73, 0x22, 0x58, 0x0a, 0x14, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x61, 0x64, 0x6f,
	0x44, 0x69, 0x73, 0x74, 0x72, 0x61, 0x63, 0x63, 0x69, 0x6f, 0x6e, 0x12, 0x2a, 0x0a, 0x10, 0x45,
	0x78, 0x69, 0x74, 0x6f, 0x44, 0x69, 0x73, 0x74, 0x72, 0x61, 0x63, 0x63, 0x69, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x45, 0x78, 0x69, 0x74, 0x6f, 0x44, 0x69, 0x73, 0x74,
	0x72, 0x61, 0x63, 0x63, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x78, 0x69, 0x74, 0x6f,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x65, 0x78, 0x69, 0x74, 0x6f, 0x22, 0x50, 0x0a,
	0x0e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x61, 0x64, 0x6f, 0x47, 0x6f, 0x6c, 0x70, 0x65, 0x12,
	0x1e, 0x0a, 0x0a, 0x45, 0x78, 0x69, 0x74, 0x6f, 0x47, 0x6f, 0x6c, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0a, 0x45, 0x78, 0x69, 0x74, 0x6f, 0x47, 0x6f, 0x6c, 0x70, 0x65, 0x12,
	0x1e, 0x0a, 0x0a, 0x42, 0x6f, 0x74, 0x69, 0x6e, 0x45, 0x78, 0x74, 0x72, 0x61, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0a, 0x42, 0x6f, 0x74, 0x69, 0x6e, 0x45, 0x78, 0x74, 0x72, 0x61, 0x22,
	0x07, 0x0a, 0x05, 0x56, 0x61, 0x63, 0x69, 0x6f, 0x32, 0x57, 0x0a, 0x0b, 0x44, 0x69, 0x73, 0x74,
	0x72, 0x61, 0x63, 0x63, 0x69, 0x6f, 0x6e, 0x12, 0x48, 0x0a, 0x11, 0x49, 0x6e, 0x69, 0x63, 0x69,
	0x6f, 0x44, 0x69, 0x73, 0x74, 0x72, 0x61, 0x63, 0x63, 0x69, 0x6f, 0x6e, 0x12, 0x13, 0x2e, 0x41,
	0x74, 0x72, 0x61, 0x63, 0x6f, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x63, 0x69, 0x6f,
	0x6e, 0x1a, 0x1c, 0x2e, 0x41, 0x74, 0x72, 0x61, 0x63, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x61, 0x64, 0x6f, 0x44, 0x69, 0x73, 0x74, 0x72, 0x61, 0x63, 0x63, 0x69, 0x6f, 0x6e, 0x22,
	0x00, 0x32, 0x45, 0x0a, 0x05, 0x47, 0x6f, 0x6c, 0x70, 0x65, 0x12, 0x3c, 0x0a, 0x0b, 0x49, 0x6e,
	0x69, 0x63, 0x69, 0x6f, 0x47, 0x6f, 0x6c, 0x70, 0x65, 0x12, 0x13, 0x2e, 0x41, 0x74, 0x72, 0x61,
	0x63, 0x6f, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x63, 0x69, 0x6f, 0x6e, 0x1a, 0x16,
	0x2e, 0x41, 0x74, 0x72, 0x61, 0x63, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x61, 0x64,
	0x6f, 0x47, 0x6f, 0x6c, 0x70, 0x65, 0x22, 0x00, 0x42, 0x13, 0x5a, 0x11, 0x67, 0x72, 0x70, 0x63,
	0x2d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_trevor_proto_rawDescOnce sync.Once
	file_trevor_proto_rawDescData = file_trevor_proto_rawDesc
)

func file_trevor_proto_rawDescGZIP() []byte {
	file_trevor_proto_rawDescOnce.Do(func() {
		file_trevor_proto_rawDescData = protoimpl.X.CompressGZIP(file_trevor_proto_rawDescData)
	})
	return file_trevor_proto_rawDescData
}

var file_trevor_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_trevor_proto_goTypes = []interface{}{
	(*Instruccion)(nil),          // 0: Atraco.Instruccion
	(*ResultadoDistraccion)(nil), // 1: Atraco.ResultadoDistraccion
	(*ResultadoGolpe)(nil),       // 2: Atraco.ResultadoGolpe
	(*Vacio)(nil),                // 3: Atraco.Vacio
}
var file_trevor_proto_depIdxs = []int32{
	0, // 0: Atraco.Distraccion.InicioDistraccion:input_type -> Atraco.Instruccion
	0, // 1: Atraco.Golpe.InicioGolpe:input_type -> Atraco.Instruccion
	1, // 2: Atraco.Distraccion.InicioDistraccion:output_type -> Atraco.ResultadoDistraccion
	2, // 3: Atraco.Golpe.InicioGolpe:output_type -> Atraco.ResultadoGolpe
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_trevor_proto_init() }
func file_trevor_proto_init() {
	if File_trevor_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_trevor_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Instruccion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trevor_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResultadoDistraccion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trevor_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResultadoGolpe); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trevor_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Vacio); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_trevor_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_trevor_proto_goTypes,
		DependencyIndexes: file_trevor_proto_depIdxs,
		MessageInfos:      file_trevor_proto_msgTypes,
	}.Build()
	File_trevor_proto = out.File
	file_trevor_proto_rawDesc = nil
	file_trevor_proto_goTypes = nil
	file_trevor_proto_depIdxs = nil
}
