// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: trevor.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Instruccion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NumTurnos     int64                  `protobuf:"varint,1,opt,name=numTurnos,proto3" json:"numTurnos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Instruccion) Reset() {
	*x = Instruccion{}
	mi := &file_trevor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Instruccion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Instruccion) ProtoMessage() {}

func (x *Instruccion) ProtoReflect() protoreflect.Message {
	mi := &file_trevor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Instruccion.ProtoReflect.Descriptor instead.
func (*Instruccion) Descriptor() ([]byte, []int) {
	return file_trevor_proto_rawDescGZIP(), []int{0}
}

func (x *Instruccion) GetNumTurnos() int64 {
	if x != nil {
		return x.NumTurnos
	}
	return 0
}

type ResultadoDistraccion struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ExitoDistraccion string                 `protobuf:"bytes,1,opt,name=ExitoDistraccion,proto3" json:"ExitoDistraccion,omitempty"`
	Exito            bool                   `protobuf:"varint,2,opt,name=exito,proto3" json:"exito,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ResultadoDistraccion) Reset() {
	*x = ResultadoDistraccion{}
	mi := &file_trevor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultadoDistraccion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultadoDistraccion) ProtoMessage() {}

func (x *ResultadoDistraccion) ProtoReflect() protoreflect.Message {
	mi := &file_trevor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultadoDistraccion.ProtoReflect.Descriptor instead.
func (*ResultadoDistraccion) Descriptor() ([]byte, []int) {
	return file_trevor_proto_rawDescGZIP(), []int{1}
}

func (x *ResultadoDistraccion) GetExitoDistraccion() string {
	if x != nil {
		return x.ExitoDistraccion
	}
	return ""
}

func (x *ResultadoDistraccion) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

type ResultadoGolpe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitoGolpe    bool                   `protobuf:"varint,1,opt,name=ExitoGolpe,proto3" json:"ExitoGolpe,omitempty"`
	BotinExtra    int64                  `protobuf:"varint,3,opt,name=BotinExtra,proto3" json:"BotinExtra,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultadoGolpe) Reset() {
	*x = ResultadoGolpe{}
	mi := &file_trevor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultadoGolpe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultadoGolpe) ProtoMessage() {}

func (x *ResultadoGolpe) ProtoReflect() protoreflect.Message {
	mi := &file_trevor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultadoGolpe.ProtoReflect.Descriptor instead.
func (*ResultadoGolpe) Descriptor() ([]byte, []int) {
	return file_trevor_proto_rawDescGZIP(), []int{2}
}

func (x *ResultadoGolpe) GetExitoGolpe() bool {
	if x != nil {
		return x.ExitoGolpe
	}
	return false
}

func (x *ResultadoGolpe) GetBotinExtra() int64 {
	if x != nil {
		return x.BotinExtra
	}
	return 0
}

type Vacio struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vacio) Reset() {
	*x = Vacio{}
	mi := &file_trevor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vacio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vacio) ProtoMessage() {}

func (x *Vacio) ProtoReflect() protoreflect.Message {
	mi := &file_trevor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vacio.ProtoReflect.Descriptor instead.
func (*Vacio) Descriptor() ([]byte, []int) {
	return file_trevor_proto_rawDescGZIP(), []int{3}
}

var File_trevor_proto protoreflect.FileDescriptor

const file_trevor_proto_rawDesc = "" +
	"\n" +
	"\ftrevor.proto\x12\x06Atraco\"+\n" +
	"\vInstruccion\x12\x1c\n" +
	"\tnumTurnos\x18\x01 \x01(\x03R\tnumTurnos\"X\n" +
	"\x14ResultadoDistraccion\x12*\n" +
	"\x10ExitoDistraccion\x18\x01 \x01(\tR\x10ExitoDistraccion\x12\x14\n" +
	"\x05exito\x18\x02 \x01(\bR\x05exito\"P\n" +
	"\x0eResultadoGolpe\x12\x1e\n" +
	"\n" +
	"ExitoGolpe\x18\x01 \x01(\bR\n" +
	"ExitoGolpe\x12\x1e\n" +
	"\n" +
	"BotinExtra\x18\x03 \x01(\x03R\n" +
	"BotinExtra\"\a\n" +
	"\x05Vacio2W\n" +
	"\vDistraccion\x12H\n" +
	"\x11InicioDistraccion\x12\x13.Atraco.Instruccion\x1a\x1c.Atraco.ResultadoDistraccion\"\x002E\n" +
	"\x05Golpe\x12<\n" +
	"\vInicioGolpe\x12\x13.Atraco.Instruccion\x1a\x16.Atraco.ResultadoGolpe\"\x00B\x13Z\x11grpc-server/protob\x06proto3"

var (
	file_trevor_proto_rawDescOnce sync.Once
	file_trevor_proto_rawDescData []byte
)

func file_trevor_proto_rawDescGZIP() []byte {
	file_trevor_proto_rawDescOnce.Do(func() {
		file_trevor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_trevor_proto_rawDesc), len(file_trevor_proto_rawDesc)))
	})
	return file_trevor_proto_rawDescData
}

var file_trevor_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_trevor_proto_goTypes = []any{
	(*Instruccion)(nil),          // 0: Atraco.Instruccion
	(*ResultadoDistraccion)(nil), // 1: Atraco.ResultadoDistraccion
	(*ResultadoGolpe)(nil),       // 2: Atraco.ResultadoGolpe
	(*Vacio)(nil),                // 3: Atraco.Vacio
}
var file_trevor_proto_depIdxs = []int32{
	0, // 0: Atraco.Distraccion.InicioDistraccion:input_type -> Atraco.Instruccion
	0, // 1: Atraco.Golpe.InicioGolpe:input_type -> Atraco.Instruccion
	1, // 2: Atraco.Distraccion.InicioDistraccion:output_type -> Atraco.ResultadoDistraccion
	2, // 3: Atraco.Golpe.InicioGolpe:output_type -> Atraco.ResultadoGolpe
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_trevor_proto_init() }
func file_trevor_proto_init() {
	if File_trevor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_trevor_proto_rawDesc), len(file_trevor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_trevor_proto_goTypes,
		DependencyIndexes: file_trevor_proto_depIdxs,
		MessageInfos:      file_trevor_proto_msgTypes,
	}.Build()
	File_trevor_proto = out.File
	file_trevor_proto_goTypes = nil
	file_trevor_proto_depIdxs = nil
}
