// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: trevor.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Distraccion_InicioDistraccion_FullMethodName = "/Atraco.Distraccion/InicioDistraccion"
)

// DistraccionClient is the client API for Distraccion service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DistraccionClient interface {
	InicioDistraccion(ctx context.Context, in *Instruccion, opts ...grpc.CallOption) (*ResultadoDistraccion, error)
}

type distraccionClient struct {
	cc grpc.ClientConnInterface
}

func NewDistraccionClient(cc grpc.ClientConnInterface) DistraccionClient {
	return &distraccionClient{cc}
}

func (c *distraccionClient) InicioDistraccion(ctx context.Context, in *Instruccion, opts ...grpc.CallOption) (*ResultadoDistraccion, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResultadoDistraccion)
	err := c.cc.Invoke(ctx, Distraccion_InicioDistraccion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DistraccionServer is the server API for Distraccion service.
// All implementations must embed UnimplementedDistraccionServer
// for forward compatibility.
type DistraccionServer interface {
	InicioDistraccion(context.Context, *Instruccion) (*ResultadoDistraccion, error)
	mustEmbedUnimplementedDistraccionServer()
}

// UnimplementedDistraccionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDistraccionServer struct{}

func (UnimplementedDistraccionServer) InicioDistraccion(context.Context, *Instruccion) (*ResultadoDistraccion, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InicioDistraccion not implemented")
}
func (UnimplementedDistraccionServer) mustEmbedUnimplementedDistraccionServer() {}
func (UnimplementedDistraccionServer) testEmbeddedByValue()                     {}

// UnsafeDistraccionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DistraccionServer will
// result in compilation errors.
type UnsafeDistraccionServer interface {
	mustEmbedUnimplementedDistraccionServer()
}

func RegisterDistraccionServer(s grpc.ServiceRegistrar, srv DistraccionServer) {
	// If the following call pancis, it indicates UnimplementedDistraccionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Distraccion_ServiceDesc, srv)
}

func _Distraccion_InicioDistraccion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Instruccion)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DistraccionServer).InicioDistraccion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Distraccion_InicioDistraccion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DistraccionServer).InicioDistraccion(ctx, req.(*Instruccion))
	}
	return interceptor(ctx, in, info, handler)
}

// Distraccion_ServiceDesc is the grpc.ServiceDesc for Distraccion service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Distraccion_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Atraco.Distraccion",
	HandlerType: (*DistraccionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InicioDistraccion",
			Handler:    _Distraccion_InicioDistraccion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "trevor.proto",
}

const (
	Golpe_InicioGolpe_FullMethodName = "/Atraco.Golpe/InicioGolpe"
)

// GolpeClient is the client API for Golpe service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GolpeClient interface {
	InicioGolpe(ctx context.Context, in *Instruccion, opts ...grpc.CallOption) (*ResultadoGolpe, error)
}

type golpeClient struct {
	cc grpc.ClientConnInterface
}

func NewGolpeClient(cc grpc.ClientConnInterface) GolpeClient {
	return &golpeClient{cc}
}

func (c *golpeClient) InicioGolpe(ctx context.Context, in *Instruccion, opts ...grpc.CallOption) (*ResultadoGolpe, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResultadoGolpe)
	err := c.cc.Invoke(ctx, Golpe_InicioGolpe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GolpeServer is the server API for Golpe service.
// All implementations must embed UnimplementedGolpeServer
// for forward compatibility.
type GolpeServer interface {
	InicioGolpe(context.Context, *Instruccion) (*ResultadoGolpe, error)
	mustEmbedUnimplementedGolpeServer()
}

// UnimplementedGolpeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGolpeServer struct{}

func (UnimplementedGolpeServer) InicioGolpe(context.Context, *Instruccion) (*ResultadoGolpe, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InicioGolpe not implemented")
}
func (UnimplementedGolpeServer) mustEmbedUnimplementedGolpeServer() {}
func (UnimplementedGolpeServer) testEmbeddedByValue()               {}

// UnsafeGolpeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GolpeServer will
// result in compilation errors.
type UnsafeGolpeServer interface {
	mustEmbedUnimplementedGolpeServer()
}

func RegisterGolpeServer(s grpc.ServiceRegistrar, srv GolpeServer) {
	// If the following call pancis, it indicates UnimplementedGolpeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Golpe_ServiceDesc, srv)
}

func _Golpe_InicioGolpe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Instruccion)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GolpeServer).InicioGolpe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Golpe_InicioGolpe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GolpeServer).InicioGolpe(ctx, req.(*Instruccion))
	}
	return interceptor(ctx, in, info, handler)
}

// Golpe_ServiceDesc is the grpc.ServiceDesc for Golpe service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Golpe_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Atraco.Golpe",
	HandlerType: (*GolpeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InicioGolpe",
			Handler:    _Golpe_InicioGolpe_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "trevor.proto",
}

const (
	PagoBotin_ConfirmarPago_FullMethodName = "/Atraco.PagoBotin/ConfirmarPago"
)

// PagoBotinClient is the client API for PagoBotin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PagoBotinClient interface {
	ConfirmarPago(ctx context.Context, in *Pago, opts ...grpc.CallOption) (*ConfirmacionPago, error)
}

type pagoBotinClient struct {
	cc grpc.ClientConnInterface
}

func NewPagoBotinClient(cc grpc.ClientConnInterface) PagoBotinClient {
	return &pagoBotinClient{cc}
}

func (c *pagoBotinClient) ConfirmarPago(ctx context.Context, in *Pago, opts ...grpc.CallOption) (*ConfirmacionPago, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmacionPago)
	err := c.cc.Invoke(ctx, PagoBotin_ConfirmarPago_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PagoBotinServer is the server API for PagoBotin service.
// All implementations must embed UnimplementedPagoBotinServer
// for forward compatibility.
type PagoBotinServer interface {
	ConfirmarPago(context.Context, *Pago) (*ConfirmacionPago, error)
	mustEmbedUnimplementedPagoBotinServer()
}

// UnimplementedPagoBotinServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPagoBotinServer struct{}

func (UnimplementedPagoBotinServer) ConfirmarPago(context.Context, *Pago) (*ConfirmacionPago, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmarPago not implemented")
}
func (UnimplementedPagoBotinServer) mustEmbedUnimplementedPagoBotinServer() {}
func (UnimplementedPagoBotinServer) testEmbeddedByValue()                   {}

// UnsafePagoBotinServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PagoBotinServer will
// result in compilation errors.
type UnsafePagoBotinServer interface {
	mustEmbedUnimplementedPagoBotinServer()
}

func RegisterPagoBotinServer(s grpc.ServiceRegistrar, srv PagoBotinServer) {
	// If the following call pancis, it indicates UnimplementedPagoBotinServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PagoBotin_ServiceDesc, srv)
}

func _PagoBotin_ConfirmarPago_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Pago)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PagoBotinServer).ConfirmarPago(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PagoBotin_ConfirmarPago_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PagoBotinServer).ConfirmarPago(ctx, req.(*Pago))
	}
	return interceptor(ctx, in, info, handler)
}

// PagoBotin_ServiceDesc is the grpc.ServiceDesc for PagoBotin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PagoBotin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Atraco.PagoBotin",
	HandlerType: (*PagoBotinServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConfirmarPago",
			Handler:    _PagoBotin_ConfirmarPago_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "trevor.proto",
}
